######################################
# UX Test Config for metaflow-dagster
######################################

scheduler:
  scheduler_type: dagster

compute_env:
  METAFLOW_DEFAULT_METADATA: local
  METAFLOW_DEFAULT_DATASTORE: local
  METAFLOW_DEFAULT_ENVIRONMENT: local
