"""
DagsterCompiler: transforms a Metaflow FlowGraph into a Dagster definitions file.

Key insight: in Metaflow, the 'start' step is special by NAME, not by type.
Its graph type is determined by what self.next() does:
  - start → single next()    → type='start'
  - start → next(a, b)       → type='split'
  - start → next(a, foreach) → type='foreach'

Generated file structure:
  1. Preamble + imports
  2. Constants   (FLOW_FILE, METAFLOW_TOP_ARGS, METAFLOW_STEP_ENV)
  3. Helpers     (_make_run_id, _run_init, _run_step, _get_foreach_splits)
  4. Config      (Pydantic Config for flow parameters)
  5. Ops         (one @op per flow step)
  6. Job         (@job composing ops)
  7. Schedule    (optional)
  8. Definitions
"""

import os
import sys
from textwrap import dedent, indent
from typing import Dict, List, Optional

from metaflow.decorators import flow_decorators
from metaflow.parameters import deploy_time_eval
from metaflow.util import dict_to_cli_options


# ──────────────────────────────────────────────────────────────────────────────
# Preamble template
# ──────────────────────────────────────────────────────────────────────────────

_PREAMBLE = '''\
"""
Dagster definitions generated by metaflow-dagster.
Flow   : {flow_name}
Job    : {job_name}
Source : {flow_file}

DO NOT EDIT — re-generate with:
    python {flow_basename} dagster create {output_file}
"""
import hashlib
import json
import os
import subprocess
import sys
from typing import Dict, List, Optional

from dagster import (
    Config,
    Definitions,
    DynamicOut,
    DynamicOutput,
    In,
    Nothing,
    OpExecutionContext,
    Out,
    Output,
    RetryPolicy,
    ScheduleDefinition,
    job,
    op,
    schedule,
)

# ── Flow constants ─────────────────────────────────────────────────────────────
FLOW_FILE = {flow_file!r}
FLOW_NAME = {flow_name!r}

# Metaflow CLI top-level flags embedded at compile time
METAFLOW_TOP_ARGS: List[str] = {top_args!r}

# Metaflow env-vars forwarded to every subprocess
METAFLOW_STEP_ENV: Dict[str, str] = {step_env!r}

# Per-step runtime decorator specs and retry limits used to honor runtime_step_cli hooks.
STEP_DECORATOR_SPECS: Dict[str, List[str]] = {step_decorator_specs!r}
STEP_MAX_USER_CODE_RETRIES: Dict[str, int] = {step_max_user_code_retries!r}
STEP_WITH_DECORATORS: Dict[str, List[str]] = {step_with_decorators!r}


# ── Execution helpers ──────────────────────────────────────────────────────────

def _make_run_id(dagster_run_id: str) -> str:
    """Derive a short, deterministic Metaflow run-id from Dagster\'s UUID."""
    return "dagster-" + hashlib.sha1(dagster_run_id.encode()).hexdigest()[:12]


def _build_env(extra: Optional[Dict[str, str]] = None) -> Dict[str, str]:
    e = {{**os.environ, **METAFLOW_STEP_ENV}}
    if extra:
        e.update(extra)
    return e


def _run_cmd(
    context: OpExecutionContext,
    cmd: List[str],
    extra_env: Optional[Dict[str, str]] = None,
) -> None:
    context.log.info("$ " + " ".join(str(c) for c in cmd))
    result = subprocess.run(
        cmd,
        env=_build_env(extra_env),
        capture_output=True,
        text=True,
        cwd=os.path.dirname(FLOW_FILE) or ".",
    )
    if result.stdout.strip():
        context.log.info(result.stdout)
    if result.stderr.strip():
        context.log.info(result.stderr)
    if result.returncode != 0:
        raise Exception(
            f"Command failed (exit {{result.returncode}}):\\n{{result.stderr[-2000:]}}"
        )


def _run_init(
    context: OpExecutionContext,
    run_id: str,
    params_task_id: str,
    parameters: Optional[Dict] = None,
) -> str:
    """Create the _parameters task. Returns its full pathspec.

    Metaflow reads parameter overrides from METAFLOW_INIT_<NAME> env vars
    (not METAFLOW_PARAMETERS). Values must be raw strings — Metaflow applies
    its own type coercion when it reads the parameter from the _parameters task.
    """
    cmd = (
        [sys.executable, FLOW_FILE]
        + METAFLOW_TOP_ARGS
        + ["init", "--run-id", run_id, "--task-id", params_task_id]
    )
    extra: Dict[str, str] = {{}}
    for k, v in (parameters or {{}}).items():
        env_key = "METAFLOW_INIT_" + k.upper().replace("-", "_")
        extra[env_key] = str(v)
    _run_cmd(context, cmd, extra or None)
    return f"{{run_id}}/_parameters/{{params_task_id}}"


def _run_step(
    context: OpExecutionContext,
    step_name: str,
    run_id: str,
    input_paths: str,
    task_id: str,
    retry_count: int = 0,
    max_user_code_retries: int = 0,
    tags: Optional[List[str]] = None,
    split_index: Optional[int] = None,
    extra_env: Optional[Dict[str, str]] = None,
) -> str:
    """Execute one Metaflow step. Returns its full task pathspec."""
    code_package_cache = _run_step.__dict__.setdefault(
        "_code_package_cache", {{"metadata": None, "sha": None, "url": None}}
    )

    def _ensure_code_package():
        if (
            code_package_cache["metadata"] is not None
            and code_package_cache["sha"] is not None
            and code_package_cache["url"] is not None
        ):
            return (
                code_package_cache["metadata"],
                code_package_cache["sha"],
                code_package_cache["url"],
            )

        import re
        import tempfile
        from metaflow.datastore import FlowDataStore
        from metaflow.plugins import DATASTORES

        with tempfile.NamedTemporaryFile(suffix=".tgz", delete=False) as tmp:
            package_path = tmp.name
        try:
            package_cmd = (
                [sys.executable, FLOW_FILE]
                + [a for a in METAFLOW_TOP_ARGS if a != "--quiet"]
                + ["package", "save", package_path]
            )
            result = subprocess.run(
                package_cmd,
                env=_build_env(),
                capture_output=True,
                text=True,
                cwd=os.path.dirname(FLOW_FILE) or ".",
            )
            if result.returncode != 0:
                raise RuntimeError(
                    "Failed to build Metaflow code package:\\n"
                    + (result.stderr or result.stdout)[-2000:]
                )
            meta_src = (result.stdout or "") + "\\n" + (result.stderr or "")
            m = re.search(r"metadata:\\s*(\\{{.*\\}})", meta_src)
            package_metadata = (
                m.group(1).strip()
                if m
                else '{{"version": 0, "archive_format": "tgz", "mfcontent_version": 1}}'
            )

            with open(package_path, "rb") as f:
                blob = f.read()

            datastore_type = next(
                (
                    a.split("--datastore=", 1)[1]
                    for a in METAFLOW_TOP_ARGS
                    if a.startswith("--datastore=")
                ),
                None,
            )
            datastore_root = next(
                (
                    a.split("--datastore-root=", 1)[1]
                    for a in METAFLOW_TOP_ARGS
                    if a.startswith("--datastore-root=")
                ),
                None,
            )
            storage_impl = next(ds for ds in DATASTORES if ds.TYPE == datastore_type)
            flow_datastore = FlowDataStore(
                FLOW_NAME,
                storage_impl=storage_impl,
                ds_root=datastore_root,
            )
            package_url, package_sha = flow_datastore.save_data([blob], len_hint=1)[0]
            code_package_cache["metadata"] = package_metadata
            code_package_cache["sha"] = package_sha
            code_package_cache["url"] = package_url
        finally:
            try:
                os.unlink(package_path)
            except Exception:
                pass

        return (
            code_package_cache["metadata"],
            code_package_cache["sha"],
            code_package_cache["url"],
        )

    class _CLIArgs:
        def __init__(self):
            self.entrypoint = [sys.executable, FLOW_FILE]
            self.top_level_args = list(METAFLOW_TOP_ARGS) + [
                f"--with={{d}}" for d in STEP_WITH_DECORATORS.get(step_name, [])
            ]
            self.commands = ["step"]
            self.command_args = [step_name]
            self.command_options = {{
                "run-id": run_id,
                "task-id": task_id,
                "input-paths": input_paths,
                "retry-count": retry_count,
                "max-user-code-retries": max_user_code_retries,
                "tag": tags or [],
                "namespace": next(
                    (
                        a.split("--namespace=", 1)[1]
                        for a in METAFLOW_TOP_ARGS
                        if a.startswith("--namespace=")
                    ),
                    "",
                ),
            }}
            if split_index is not None:
                self.command_options["split-index"] = split_index
            self.env: Dict[str, str] = {{}}

        def _options(self, mapping):
            for k, v in mapping.items():
                if v is None or v is False:
                    continue
                if k == "decospecs":
                    k = "with"
                k = k.replace("_", "-")
                vals = v if isinstance(v, (list, tuple, set)) else [v]
                for value in vals:
                    yield f"--{{k}}"
                    if not isinstance(value, bool):
                        if isinstance(value, tuple):
                            for vv in value:
                                yield str(vv)
                        else:
                            yield str(value)

        def get_args(self):
            args = list(self.entrypoint)
            args.extend(self.top_level_args)
            args.extend(self.commands)
            args.extend(
                str(arg) if arg is not None else "" for arg in self.command_args
            )
            args.extend(self._options(self.command_options))
            return args

    cli_args = _CLIArgs()

    from metaflow.decorators import extract_step_decorator_from_decospec

    for spec in STEP_DECORATOR_SPECS.get(step_name, []):
        deco, _ = extract_step_decorator_from_decospec(spec)
        if (
            hasattr(deco, "package_metadata")
            and hasattr(deco, "package_sha")
            and hasattr(deco, "package_url")
            and getattr(deco, "package_metadata", None) is None
        ):
            package_metadata, package_sha, package_url = _ensure_code_package()
            deco.package_metadata = package_metadata
            deco.package_sha = package_sha
            deco.package_url = package_url
        deco.runtime_step_cli(cli_args, retry_count, max_user_code_retries, None)

    cmd = cli_args.get_args()
    merged_env = dict(cli_args.env)
    if extra_env:
        merged_env.update(extra_env)
    _run_cmd(context, cmd, merged_env or None)
    return f"{{run_id}}/{{step_name}}/{{task_id}}"


def _get_foreach_splits(run_id: str, step_name: str, task_id: str) -> int:
    """Read the foreach cardinality directly from the local datastore files.

    Reads <ds_root>/<flow>/<run>/<step>/<task>/0.data.json to find the SHA of
    _foreach_num_splits, then decompresses the gzip+pickle blob.
    Bypasses the Metaflow metadata service to avoid import-time caching issues.
    """
    import gzip
    import pickle
    ds_root = next(
        (a.split("--datastore-root=")[1] for a in METAFLOW_TOP_ARGS if a.startswith("--datastore-root=")),
        os.environ.get("METAFLOW_DATASTORE_SYSROOT_LOCAL", ""),
    )
    try:
        data_json_path = os.path.join(ds_root, FLOW_NAME, run_id, step_name, task_id, "0.data.json")
        with open(data_json_path) as fh:
            data_map = json.load(fh)
        sha = data_map["objects"]["_foreach_num_splits"]
        blob_path = os.path.join(ds_root, FLOW_NAME, "data", sha[:2], sha)
        with gzip.open(blob_path, "rb") as fh:
            return int(pickle.load(fh))
    except Exception as exc:
        raise RuntimeError(
            f"Could not read foreach splits for {{step_name!r}}: {{exc}}"
        ) from exc


def _add_step_metadata(
    context: OpExecutionContext,
    task_path: str,
    output_name: Optional[str] = None,
) -> None:
    """Emit artifact-key metadata to the Dagster UI.

    Reads the 0.data.json index from the local datastore so Dagster can show
    which Metaflow artifact keys exist for this step. Does NOT load artifact
    values — they remain in the Metaflow datastore. Also emits a Python
    snippet showing how to retrieve each artifact via the Metaflow Task API.
    """
    from dagster import MetadataValue
    parts = task_path.split("/")
    if len(parts) < 3:
        return
    run_id, step_name, task_id = parts[0], parts[1], parts[2]
    ds_root = next(
        (a.split("--datastore-root=")[1] for a in METAFLOW_TOP_ARGS
         if a.startswith("--datastore-root=")),
        os.environ.get("METAFLOW_DATASTORE_SYSROOT_LOCAL", ""),
    )
    data_json_path = os.path.join(
        ds_root, FLOW_NAME, run_id, step_name, task_id, "0.data.json"
    )
    try:
        with open(data_json_path) as fh:
            objects = json.load(fh).get("objects", {{}})
    except Exception:
        return
    keys = [k for k in objects if not k.startswith("_")]
    if not keys:
        return
    pathspec = "/".join([FLOW_NAME, run_id, step_name, task_id])
    lines = ["from metaflow import Task", "task = Task(" + repr(pathspec) + ")"]
    lines += ["task[" + repr(k) + "].data  # " + k for k in keys]
    snippet = "\\n".join(lines)
    meta = {{
        "artifact_keys": MetadataValue.md(
            "**Metaflow artifacts:** " + ", ".join("`" + k + "`" for k in keys)
        ),
        "retrieve (copy ↓)": MetadataValue.text(snippet),
    }}
    kwargs = {{"output_name": output_name}} if output_name is not None else {{}}
    try:
        context.add_output_metadata(meta, **kwargs)
    except Exception:
        pass


'''


# ──────────────────────────────────────────────────────────────────────────────
# Compiler
# ──────────────────────────────────────────────────────────────────────────────

class DagsterCompiler:
    def __init__(
        self,
        job_name: str,
        graph,
        flow,
        flow_file: str,
        metadata,
        environment,
        flow_datastore,
        event_logger,
        monitor,
        tags: List[str],
        with_decorators: List[str],
        namespace: Optional[str],
        username: str,
        max_workers: int,
        workflow_timeout: Optional[int],
        step_env: Dict[str, str],
    ):
        self.job_name = job_name
        self.graph = graph
        self.flow = flow
        self.flow_file = flow_file
        self.metadata = metadata
        self.environment = environment
        self.flow_datastore = flow_datastore
        self.event_logger = event_logger
        self.monitor = monitor
        self.tags = tags
        self.with_decorators = with_decorators
        self.namespace = namespace
        self.username = username
        self.max_workers = max_workers
        self.workflow_timeout = workflow_timeout
        self.step_env = step_env

        self.flow_name = flow.name
        self.parameters = self._extract_parameters()
        self.schedule = self._extract_schedule()

    # ── Public ─────────────────────────────────────────────────────────────────

    def compile(self) -> str:
        parts = [self._render_preamble()]
        config = self._render_config_class()
        if config:
            parts.append(config)
        # Determine which steps are handled inside compound ops and should not
        # get their own top-level @op definition.
        chains = self._foreach_chains()
        steps_in_compound: set = set()
        for outer_name, chain in chains.items():
            if len(chain) > 1:
                for d in range(1, len(chain)):
                    _, body_n, join_n = chain[d]
                    steps_in_compound.add(body_n)
                    steps_in_compound.add(join_n)
                # The outer body (chain[0][1]) is itself a foreach step; it is also
                # handled inside the compound op body, NOT emitted as a standalone op.
                steps_in_compound.add(chain[0][1])
        for node in self._topological_order():
            if node.name not in steps_in_compound:
                parts.append(self._render_op(node))
        # Emit compound ops for any nested foreach chains
        for outer_name, chain in chains.items():
            if len(chain) > 1:
                parts.append(self._render_nested_foreach_compound_op(chain))
        parts.append(self._render_job())
        if self.schedule:
            parts.append(self._render_schedule())
        parts.append(self._render_definitions())
        return "\n\n".join(p for p in parts if p.strip()) + "\n"

    # ── Preamble ───────────────────────────────────────────────────────────────

    def _render_preamble(self) -> str:
        return _PREAMBLE.format(
            flow_name=self.flow_name,
            job_name=self.job_name,
            flow_file=self.flow_file,
            flow_basename=os.path.basename(self.flow_file),
            output_file="<output.py>",
            top_args=self._build_top_args(),
            step_env=self.step_env,
            step_decorator_specs=self._build_step_decorator_specs(),
            step_max_user_code_retries=self._build_step_max_user_code_retries(),
            step_with_decorators=self._build_step_with_decorators(),
        )

    def _build_top_args(self) -> List[str]:
        top_opts_dict: Dict = {}
        for deco in flow_decorators(self.flow):
            top_opts_dict.update(deco.get_top_level_options())
        top_opts = list(dict_to_cli_options(top_opts_dict))
        args = top_opts + [
            "--quiet",
            "--no-pylint",
            "--metadata=%s" % self.metadata.TYPE,
            "--environment=%s" % self.environment.TYPE,
            "--datastore=%s" % self.flow_datastore.TYPE,
            "--datastore-root=%s" % self.flow_datastore.datastore_root,
            "--event-logger=%s" % self.event_logger.TYPE,
            "--monitor=%s" % self.monitor.TYPE,
        ]
        if self.namespace:
            args.append("--namespace=%s" % self.namespace)
        return args

    def _build_step_decorator_specs(self) -> Dict[str, List[str]]:
        specs = {}
        for node in self._topological_order():
            step_specs = [d.make_decorator_spec() for d in node.decorators]
            step_specs.extend(self.with_decorators)
            specs[node.name] = step_specs
        return specs

    def _build_step_max_user_code_retries(self) -> Dict[str, int]:
        retries = {}
        for node in self._topological_order():
            max_retries, _ = self._get_retry_info(node)
            retries[node.name] = max_retries
        return retries

    def _build_step_with_decorators(self) -> Dict[str, List[str]]:
        return {node.name: list(self.with_decorators) for node in self._topological_order()}

    # ── Config class ───────────────────────────────────────────────────────────

    def _extract_parameters(self) -> List[Dict]:
        params = []
        for var, param in self.flow._get_parameters():
            default = deploy_time_eval(param.kwargs.get("default"))
            params.append({
                "name": param.name,
                "var": var,
                "default": default,
                "help": param.kwargs.get("help", ""),
                "type": type(default).__name__ if default is not None else "str",
            })
        return params

    def _render_config_class(self) -> str:
        if not self.parameters:
            return ""
        lines = [f"class {self.flow_name}Config(Config):"]
        for p in self.parameters:
            default = p["default"]
            type_name = p["type"]
            if type_name == "bool":
                ann, val = "bool", default
            elif type_name == "int":
                ann, val = "int", default
            elif type_name == "float":
                ann, val = "float", default
            else:
                ann, val = "str", str(default) if default is not None else ""
            comment = f"  # {p['help']}" if p["help"] else ""
            lines.append(f"    {p['name']}: {ann} = {val!r}{comment}")
        return "\n".join(lines)

    # ── Op rendering ───────────────────────────────────────────────────────────

    def _topological_order(self):
        visited = set()
        queue = [self.graph["start"]]
        result = []
        while queue:
            node = queue.pop(0)
            if node.name in visited:
                continue
            visited.add(node.name)
            result.append(node)
            for child in node.out_funcs:
                queue.append(self.graph[child])
        return result

    def _op_name(self, step_name: str) -> str:
        return f"op_{step_name}"

    def _render_op(self, node) -> str:
        # The "start" step is special regardless of its graph type
        if node.name == "start":
            return self._render_start_op(node)
        ntype = node.type
        if ntype == "end":
            return self._render_end_op(node)
        elif ntype in ("linear",):
            return self._render_linear_op(node)
        elif ntype == "join":
            return self._render_join_op(node)
        elif ntype == "split":
            return self._render_split_op(node)
        elif ntype == "foreach":
            return self._render_foreach_op(node)
        else:
            raise NotImplementedError(f"Unsupported node type: {ntype!r} for step {node.name!r}")

    # ── Per-step decorator helpers ─────────────────────────────────────────────

    def _get_retry_info(self, node):
        """Returns (max_retries, delay_seconds_or_None) from @retry decorator."""
        max_retries = 0
        for deco in node.decorators:
            try:
                user_retries, _ = deco.step_task_retry_count()
                max_retries = max(max_retries, user_retries)
            except Exception:
                pass
        delay_seconds = None
        for deco in node.decorators:
            if deco.name == "retry":
                mins = deco.attributes.get("minutes_between_retries", 0)
                if mins:
                    delay_seconds = int(mins) * 60
                break
        return max_retries, delay_seconds

    def _get_timeout_seconds(self, node) -> Optional[int]:
        """Returns timeout in seconds from @timeout decorator, or None."""
        for deco in node.decorators:
            if deco.name == "timeout":
                secs = int(deco.attributes.get("seconds") or 0)
                mins = int(deco.attributes.get("minutes") or 0)
                hours = int(deco.attributes.get("hours") or 0)
                total = secs + mins * 60 + hours * 3600
                if total > 0:
                    return total
        return None

    def _get_env_vars(self, node) -> Dict[str, str]:
        """Returns env vars dict from @environment decorator."""
        for deco in node.decorators:
            if deco.name == "environment":
                return deco.attributes.get("vars") or {}
        return {}

    def _op_decorator_str(self, node, ins_spec: str = "", out_spec: str = "") -> str:
        """Build '@op(...)' string, including retry_policy and tags if applicable."""
        max_retries, delay_seconds = self._get_retry_info(node)
        timeout_seconds = self._get_timeout_seconds(node)

        parts = []
        if ins_spec:
            parts.append(f"ins={ins_spec}")
        if out_spec:
            parts.append(f"out={out_spec}")
        if max_retries > 0:
            if delay_seconds:
                parts.append(f"retry_policy=RetryPolicy(max_retries={max_retries}, delay={delay_seconds})")
            else:
                parts.append(f"retry_policy=RetryPolicy(max_retries={max_retries})")
        if timeout_seconds:
            parts.append(f'tags={{"dagster/op_execution_timeout": "{timeout_seconds}"}}')
        return f"@op({', '.join(parts)})"

    def _extra_env_code(self, node) -> str:
        """Returns a Python dict literal for @environment vars, or 'None'."""
        env_vars = self._get_env_vars(node)
        return repr(env_vars) if env_vars else "None"

    # start op (handles any start type) ───────────────────────────────────────

    def _render_start_op(self, node) -> str:
        """The start step always runs init+step; outputs depend on its graph type."""
        ntype = node.type  # 'start', 'split', or 'foreach'
        config_ann = f", config: {self.flow_name}Config" if self.parameters else ""
        param_dict = (
            "{" + ", ".join(f'"{p["name"]}": config.{p["name"]}' for p in self.parameters) + "}"
            if self.parameters else "{}"
        )
        tags_code = repr(self.tags)
        env_code = self._extra_env_code(node)

        # The common body: init then step
        common = (
            f'    run_id = _make_run_id(context.run_id)\n'
            f'    parameters = {param_dict}\n'
            f'    params_path = _run_init(context, run_id, "params", parameters)\n'
            f'    task_path = _run_step(\n'
            f'        context, "start", run_id, params_path, "1",\n'
            f'        retry_count=context.retry_number,\n'
            f'        max_user_code_retries=STEP_MAX_USER_CODE_RETRIES["start"],\n'
            f'        tags={tags_code},\n'
            f'        extra_env={env_code},\n'
            f'    )\n'
        )

        if ntype in ("start", "linear"):
            deco = self._op_decorator_str(node, out_spec="Out(str)")
            return (
                f'{deco}\n'
                f'def {self._op_name("start")}(context: OpExecutionContext{config_ann}) -> str:\n'
                + common
                + f'    _add_step_metadata(context, task_path)\n'
                + f'    return task_path\n'
            )
        elif ntype == "split":
            branches = node.out_funcs
            first_branch = branches[0]
            out_spec = "{" + ", ".join(f'"{b}": Out(str)' for b in branches) + "}"
            deco = self._op_decorator_str(node, out_spec=out_spec)
            yields = "".join(
                f'    yield Output(task_path, output_name="{b}")\n' for b in branches
            )
            return (
                f'{deco}\n'
                f'def {self._op_name("start")}(context: OpExecutionContext{config_ann}):\n'
                + common
                + f'    _add_step_metadata(context, task_path, output_name="{first_branch}")\n'
                + yields
            )
        elif ntype == "foreach":
            deco = self._op_decorator_str(node, out_spec="DynamicOut(str)")
            return (
                f'{deco}\n'
                f'def {self._op_name("start")}(context: OpExecutionContext{config_ann}):\n'
                + common
                + f'    _add_step_metadata(context, task_path)\n'
                + f'    num_splits = _get_foreach_splits(run_id, "start", "1")\n'
                + f'    for _i in range(num_splits):\n'
                + f'        yield DynamicOutput(f"{{task_path}}//_i={{_i}}", mapping_key=str(_i))\n'
            )
        else:
            raise NotImplementedError(f"start step with type {ntype!r}")

    # end op ───────────────────────────────────────────────────────────────────

    def _render_end_op(self, node) -> str:
        in_name = node.in_funcs[0] if node.in_funcs else "upstream"
        tags = repr(self.tags)
        env_code = self._extra_env_code(node)
        max_retries, _ = self._get_retry_info(node)
        ins_spec = '{"' + in_name + '": In(str)}'
        deco = self._op_decorator_str(node, ins_spec=ins_spec)
        return dedent(f"""\
            {deco}
            def {self._op_name(node.name)}(context: OpExecutionContext, {in_name}: str) -> None:
                run_id = {in_name}.split("/")[0]
                _run_step(context, "end", run_id, {in_name}, "1",
                    retry_count=context.retry_number, max_user_code_retries={max_retries},
                    tags={tags}, extra_env={env_code})
        """)

    # linear op ────────────────────────────────────────────────────────────────

    def _render_linear_op(self, node) -> str:
        parent_is_foreach = any(
            self.graph[p].type == "foreach" or (p == "start" and self.graph["start"].type == "foreach")
            for p in node.in_funcs
        )
        in_name = node.in_funcs[0] if node.in_funcs else "upstream"
        tags = repr(self.tags)
        env_code = self._extra_env_code(node)
        max_retries, _ = self._get_retry_info(node)
        ins_spec = '{"' + in_name + '": In(str)}'
        deco = self._op_decorator_str(node, ins_spec=ins_spec, out_spec="Out(str)")

        if parent_is_foreach:
            # Body step of a foreach: receives encoded task_path + split index
            return dedent(f"""\
                {deco}
                def {self._op_name(node.name)}(context: OpExecutionContext, {in_name}: str) -> str:
                    # {in_name} = "run_id/step/task_id//_i=N"
                    parts = {in_name}.split("//_i=")
                    base_path, split_index = parts[0], int(parts[1]) if len(parts) > 1 else 0
                    run_id = base_path.split("/")[0]
                    task_id = f"1-{{split_index}}"
                    task_path = _run_step(
                        context, "{node.name}", run_id, base_path, task_id,
                        retry_count=context.retry_number,
                        max_user_code_retries={max_retries},
                        tags={tags},
                        split_index=split_index,
                        extra_env={env_code},
                    )
                    _add_step_metadata(context, task_path)
                    return task_path
            """)
        else:
            return dedent(f"""\
                {deco}
                def {self._op_name(node.name)}(context: OpExecutionContext, {in_name}: str) -> str:
                    run_id = {in_name}.split("/")[0]
                    task_path = _run_step(context, "{node.name}", run_id, {in_name}, "1",
                        retry_count=context.retry_number, max_user_code_retries={max_retries},
                        tags={tags}, extra_env={env_code})
                    _add_step_metadata(context, task_path)
                    return task_path
            """)

    # split op ─────────────────────────────────────────────────────────────────

    def _render_split_op(self, node) -> str:
        in_name = node.in_funcs[0] if node.in_funcs else "upstream"
        branches = node.out_funcs
        first_branch = branches[0]
        out_spec = "{" + ", ".join(f'"{b}": Out(str)' for b in branches) + "}"
        ins_spec = '{"' + in_name + '": In(str)}'
        tags = repr(self.tags)
        env_code = self._extra_env_code(node)
        max_retries, _ = self._get_retry_info(node)
        deco = self._op_decorator_str(node, ins_spec=ins_spec, out_spec=out_spec)
        yields = "\n    ".join(
            f'yield Output(task_path, output_name="{b}")' for b in branches
        )
        return dedent(f"""\
            {deco}
            def {self._op_name(node.name)}(context: OpExecutionContext, {in_name}: str):
                run_id = {in_name}.split("/")[0]
                task_path = _run_step(context, "{node.name}", run_id, {in_name}, "1",
                    retry_count=context.retry_number, max_user_code_retries={max_retries},
                    tags={tags}, extra_env={env_code})
                _add_step_metadata(context, task_path, output_name="{first_branch}")
                {yields}
        """)

    # join op ──────────────────────────────────────────────────────────────────

    def _render_join_op(self, node) -> str:
        is_foreach_join = bool(
            node.split_parents
            and (
                self.graph[node.split_parents[-1]].type == "foreach"
                or node.split_parents[-1] == "start" and self.graph["start"].type == "foreach"
            )
        )
        tags = repr(self.tags)
        env_code = self._extra_env_code(node)
        max_retries, _ = self._get_retry_info(node)

        if is_foreach_join:
            in_name = "foreach_results"
            ins_spec = '{"foreach_results": In(list)}'
            deco = self._op_decorator_str(node, ins_spec=ins_spec, out_spec="Out(str)")
            return dedent(f"""\
                {deco}
                def {self._op_name(node.name)}(context: OpExecutionContext, {in_name}: list) -> str:
                    run_id = {in_name}[0].split("/")[0]
                    from metaflow.util import compress_list
                    clean = [{in_name}[i].split("//_i=")[0] for i in range(len({in_name}))]
                    input_paths = compress_list(clean)
                    task_path = _run_step(context, "{node.name}", run_id, input_paths, "1",
                        retry_count=context.retry_number, max_user_code_retries={max_retries},
                        tags={tags}, extra_env={env_code})
                    _add_step_metadata(context, task_path)
                    return task_path
            """)
        else:
            # Regular split-join: receives one input per branch
            ins_parts = [f'"{p}": In(str)' for p in node.in_funcs]
            ins_spec = "{" + ", ".join(ins_parts) + "}"
            args = ", ".join(node.in_funcs)
            paths_list = "[" + ", ".join(node.in_funcs) + "]"
            deco = self._op_decorator_str(node, ins_spec=ins_spec, out_spec="Out(str)")
            return dedent(f"""\
                {deco}
                def {self._op_name(node.name)}(context: OpExecutionContext, {args}) -> str:
                    run_id = {node.in_funcs[0]}.split("/")[0]
                    from metaflow.util import compress_list
                    input_paths = compress_list({paths_list})
                    task_path = _run_step(context, "{node.name}", run_id, input_paths, "1",
                        retry_count=context.retry_number, max_user_code_retries={max_retries},
                        tags={tags}, extra_env={env_code})
                    _add_step_metadata(context, task_path)
                    return task_path
            """)

    # foreach op ───────────────────────────────────────────────────────────────

    def _render_foreach_op(self, node) -> str:
        in_name = node.in_funcs[0] if node.in_funcs else "upstream"
        tags = repr(self.tags)
        env_code = self._extra_env_code(node)
        max_retries, _ = self._get_retry_info(node)
        ins_spec = '{"' + in_name + '": In(str)}'
        deco = self._op_decorator_str(node, ins_spec=ins_spec, out_spec="DynamicOut(str)")
        # Note: we use _i to avoid clashing with any user variable names
        # The f-string in generated code: we must use non-f-string concat to avoid
        # the compiler's own f-string from interpolating {_i} prematurely.
        return dedent(f"""\
            {deco}
            def {self._op_name(node.name)}(context: OpExecutionContext, {in_name}: str):
                run_id = {in_name}.split("/")[0]
                task_path = _run_step(context, "{node.name}", run_id, {in_name}, "1",
                    retry_count=context.retry_number, max_user_code_retries={max_retries},
                    tags={tags}, extra_env={env_code})
                _add_step_metadata(context, task_path)
                num_splits = _get_foreach_splits(run_id, "{node.name}", "1")
                for _i in range(num_splits):
                    yield DynamicOutput(task_path + "//_i=" + str(_i), mapping_key=str(_i))
        """)

    # ── Foreach chain analysis ─────────────────────────────────────────────────

    def _foreach_chains(self) -> Dict[str, List]:
        """Return {outermost_foreach: chain} for every outermost foreach in the flow.

        Each chain is a list of (foreach_name, body_name, join_name) tuples ordered
        outermost-first.  The chain ends when body_name is NOT itself a foreach step,
        so len(chain) == 1 for a simple (non-nested) foreach.
        """
        # foreach step name -> immediate body step name
        foreach_body: Dict[str, str] = {}
        for node in self._topological_order():
            is_foreach = (
                node.type == "foreach"
                or (node.name == "start" and self.graph["start"].type == "foreach")
            )
            if is_foreach and node.out_funcs:
                foreach_body[node.name] = node.out_funcs[0]

        # foreach steps that are themselves the body of another foreach
        nested_foreach = {body for body in foreach_body.values() if body in foreach_body}
        # outermost = foreach steps not nested inside another foreach
        outermost = [name for name in foreach_body if name not in nested_foreach]

        chains: Dict[str, List] = {}
        for outer in outermost:
            chain: List = []
            current = outer
            while True:
                body = foreach_body[current]
                # Find the join step whose split_parents[-1] == current
                join = None
                for node in self._topological_order():
                    if node.type == "join" and node.split_parents:
                        if node.split_parents[-1] == current:
                            join = node.name
                            break
                if join is None:
                    break
                chain.append((current, body, join))
                if body in foreach_body:
                    current = body
                else:
                    break
            if chain:
                chains[outer] = chain

        return chains

    # ── Compound op for nested foreach chains ─────────────────────────────────

    def _compound_op_name(self, outer_foreach_name: str) -> str:
        """Name for the compound op that handles the body of an outer foreach."""
        return "op_%s__body" % outer_foreach_name

    def _render_nested_foreach_compound_op(self, chain: List) -> str:
        """Generate a compound op for the body of an outer foreach in a nested chain.

        Dagster cannot have an op be downstream of more than one dynamic output
        (nested .map() is not supported).  For any foreach chain of depth > 1 we
        therefore generate a single @op that:

          1.  Receives the outer foreach's DynamicOutput value (encoded path + //_i=N).
          2.  Runs the outer body step (which is itself a foreach step).
          3.  Loops over inner foreach splits.
          4.  For each inner split runs the leaf body step(s).
          5.  Runs the inner join step to collect inner results.
          6.  Returns the inner join task path.

        This op is then used with .map() on the outer foreach's DynamicOutput so
        that the outer join can use .collect() on the results.
        """
        outer_foreach_name = chain[0][0]
        compound_name = self._compound_op_name(outer_foreach_name)
        in_name = outer_foreach_name
        ins_spec = '{"' + in_name + '": In(str)}'

        body_lines = self._compound_op_body_lines(chain, param_name=in_name)
        body_text = "\n".join("    " + line for line in body_lines)
        return (
            "@op(ins=%s, out=Out(str))\n"
            "def %s(context: OpExecutionContext, %s: str) -> str:\n"
            "%s\n"
        ) % (ins_spec, compound_name, in_name, body_text)

    def _compound_op_body_lines(self, chain: List, param_name: str) -> List[str]:
        """Generate body lines for a compound op that handles nested foreach.

        The compound op is the BODY used with .map() on the outermost foreach's
        DynamicOutput.  chain[0] = (outer_foreach, outer_body=inner_foreach, outer_join).
        The compound op:
          - Receives the outer_foreach's DynamicOutput value ("run_id/step/tid//_i=N")
          - Does NOT re-run outer_foreach (already run by op_outer_foreach in the job)
          - Runs outer_body (chain[0][1]) which is itself a foreach step
          - Recursively handles deeper levels using chain[1:]
          - Runs the innermost join (chain[-1][2])
          - Returns the innermost join's task path
          - outer_join (chain[0][2]) is handled EXTERNALLY via .collect()

        For chain = [(start, outer_step, outer_join), (outer_step, inner_step, inner_join)]:
          1. Decode "run_id/start/1//_i=N" -> run_id, outer_foreach_task_id="1", outer_split=N
          2. Run outer_step at task_id "1-N" with input = "run_id/start/1"
          3. Read outer_step's num_splits
          4. For each _i in range(num_splits):
               Run inner_step at task_id "1-N-{_i}"
               Append inner_step path to results
          5. Run inner_join at task_id "1-N-join"
          6. return inner_join path
        """
        tags_code = repr(self.tags)
        _IDX = ["_i", "_j", "_k", "_l", "_m"]

        # Use a list to collect lines (allows nested function to append to it)
        result_lines: List[str] = []

        # Decode outer DynamicOutput value
        result_lines.append("_parts = %s.split('//_i=')" % param_name)
        result_lines.append("_base_path = _parts[0]")
        result_lines.append("_outer_split = int(_parts[1]) if len(_parts) > 1 else 0")
        result_lines.append("run_id = _base_path.split('/')[0]")
        # Outer foreach task_id is the last path component
        result_lines.append("_outer_fe_tid = _base_path.rsplit('/', 1)[-1]")

        inner_chain = chain[1:]  # chain starting from the inner_foreach level

        def _emit(depth: int, indent: str, parent_path_expr: str, parent_task_id_var: str, split_var: str) -> str:
            """Emit code for inner_chain[depth].  Returns the join_path variable name."""
            foreach_name, body_name, join_name = inner_chain[depth]
            idx = _IDX[depth] if depth < len(_IDX) else "_idx_%d" % depth

            foreach_node = self.graph[foreach_name]
            foreach_env = self._extra_env_code(foreach_node)
            foreach_max_retries, _ = self._get_retry_info(foreach_node)
            join_node = self.graph[join_name]
            join_env = self._extra_env_code(join_node)
            join_max_retries, _ = self._get_retry_info(join_node)

            # Task IDs and variable names unique per depth
            fe_tid_var = "_fe_tid_%d" % depth
            fe_path_var = "_fe_path_%d" % depth
            results_var = "_res_%d" % depth
            join_tid_var = "_join_tid_%d" % depth
            join_path_var = "_join_path_%d" % depth

            # Compute foreach step's task_id from parent
            result_lines.append(
                indent + '%s = %s + "-" + str(%s)'
                % (fe_tid_var, parent_task_id_var, split_var)
            )

            # Run the foreach step
            result_lines.append(indent + "%s = _run_step(" % fe_path_var)
            result_lines.append(indent + "    context, %r, run_id, %s," % (foreach_name, parent_path_expr))
            result_lines.append(indent + "    %s," % fe_tid_var)
            result_lines.append(indent + "    retry_count=context.retry_number,")
            result_lines.append(indent + "    max_user_code_retries=%d," % foreach_max_retries)
            result_lines.append(indent + "    tags=%s," % tags_code)
            result_lines.append(indent + "    split_index=%s," % split_var)
            result_lines.append(indent + "    extra_env=%s," % foreach_env)
            result_lines.append(indent + ")")
            result_lines.append(indent + "_add_step_metadata(context, %s)" % fe_path_var)

            # Read num_splits
            result_lines.append(
                indent + "_ns_%d = _get_foreach_splits(run_id, %r, %s)"
                % (depth, foreach_name, fe_tid_var)
            )

            # Initialize results list
            result_lines.append(indent + "%s = []" % results_var)
            result_lines.append(indent + "for %s in range(_ns_%d):" % (idx, depth))

            if depth == len(inner_chain) - 1:
                # Innermost: body_name is a regular (non-foreach) step
                body_node = self.graph[body_name]
                body_env = self._extra_env_code(body_node)
                body_max_retries, _ = self._get_retry_info(body_node)
                body_tid_var = "_body_tid_%d" % depth
                body_path_var = "_body_path_%d" % depth
                result_lines.append(indent + '    %s = %s + "-" + str(%s)' % (body_tid_var, fe_tid_var, idx))
                result_lines.append(indent + "    %s = _run_step(" % body_path_var)
                result_lines.append(indent + "        context, %r, run_id, %s," % (body_name, fe_path_var))
                result_lines.append(indent + "        %s," % body_tid_var)
                result_lines.append(indent + "        retry_count=context.retry_number,")
                result_lines.append(indent + "        max_user_code_retries=%d," % body_max_retries)
                result_lines.append(indent + "        tags=%s," % tags_code)
                result_lines.append(indent + "        split_index=%s," % idx)
                result_lines.append(indent + "        extra_env=%s," % body_env)
                result_lines.append(indent + "    )")
                result_lines.append(indent + "    _add_step_metadata(context, %s)" % body_path_var)
                result_lines.append(indent + "    %s.append(%s)" % (results_var, body_path_var))
            else:
                # body is itself a foreach step: recurse (body_name == inner_chain[depth+1][0])
                inner_join_var = _emit(depth + 1, indent + "    ", fe_path_var, fe_tid_var, idx)
                result_lines.append(indent + "    %s.append(%s)" % (results_var, inner_join_var))

            # After loop: run join
            result_lines.append(indent + "from metaflow.util import compress_list")
            result_lines.append(indent + "_ji_%d = compress_list(%s)" % (depth, results_var))
            result_lines.append(indent + '%s = %s + "-join"' % (join_tid_var, fe_tid_var))
            result_lines.append(indent + "%s = _run_step(" % join_path_var)
            result_lines.append(indent + "    context, %r, run_id, _ji_%d," % (join_name, depth))
            result_lines.append(indent + "    %s," % join_tid_var)
            result_lines.append(indent + "    retry_count=context.retry_number,")
            result_lines.append(indent + "    max_user_code_retries=%d," % join_max_retries)
            result_lines.append(indent + "    tags=%s," % tags_code)
            result_lines.append(indent + "    extra_env=%s," % join_env)
            result_lines.append(indent + ")")
            result_lines.append(indent + "_add_step_metadata(context, %s)" % join_path_var)
            return join_path_var

        # Emit depth 0 of the inner chain.
        # At depth 0: the foreach step is inner_chain[0][0], its input is _base_path,
        # and its task_id prefix is _outer_fe_tid with split index _outer_split.
        final_var = _emit(0, "", "_base_path", "_outer_fe_tid", "_outer_split")
        result_lines.append("return %s" % final_var)
        return result_lines

    # ── Job body ───────────────────────────────────────────────────────────────

    def _render_job(self) -> str:
        body = self._generate_job_body()
        # Build manually — dedent(f"""...""") mishandles multi-line substitutions
        body_indented = "\n".join("    " + line for line in body.splitlines())
        if self.workflow_timeout:
            tags_arg = f'tags={{"dagster/max_runtime": "{self.workflow_timeout}"}}'
            return f"@job({tags_arg})\ndef {self.job_name}():\n{body_indented}\n"
        return f"@job\ndef {self.job_name}():\n{body_indented}\n"

    def _generate_job_body(self) -> str:
        """
        Walk the graph BFS and emit assignment statements.
        var_map: step_name -> Python expression for its output.

        For nested foreach chains (depth > 1), steps inside the chain are handled
        by the compound op and are therefore skipped in the top-level job body.
        The compound op is wired via .map() on the outer foreach's DynamicOutput
        and its result (the inner join's task path) is used by .collect() for the
        outer join.
        """
        lines: List[str] = []
        var_map: Dict[str, str] = {}

        # Build foreach chain info to identify nested steps that are handled
        # by compound ops and must be skipped in the top-level job body.
        chains = self._foreach_chains()

        # nested_body_steps: step names that are the body of a foreach in a nested chain
        # nested_inner_joins: the inner join steps that are inside compound ops
        # For each nested chain (depth > 1):
        #   - chain[0] = (outer_foreach, outer_body=inner_foreach, outer_join)
        #   - chain[1..] = (inner_foreach, inner_body, inner_join), ...
        # The compound op replaces outer_body (and everything inside the chain from chain[1:])
        # In the job body:
        #   - outer_foreach: still emitted normally (DynamicOut)
        #   - outer_body..inner_join: all SKIPPED (inside compound op)
        #   - outer_join: emitted with .collect() on the compound op's mapped output
        #   - compound op result var is stored under outer_body name for the join lookup

        # steps_in_compound: set of step names handled inside some compound op
        steps_in_compound: set = set()
        # compound_parent_for_join: outer_join -> outer_foreach name
        # (so we know to use compound_op for the .collect())
        compound_info: Dict[str, str] = {}  # outer_join_name -> outer_foreach_name

        for outer_name, chain in chains.items():
            if len(chain) > 1:
                # The outer_body is chain[0][1], which is itself a foreach step.
                # All steps from chain[1] onward (the inner chain) are inside the compound op.
                outer_foreach_name, outer_body_name, outer_join_name = chain[0]
                # Skip: outer_body and everything deeper
                steps_in_compound.add(outer_body_name)
                for d in range(1, len(chain)):
                    _, body_n, join_n = chain[d]
                    steps_in_compound.add(body_n)
                    steps_in_compound.add(join_n)
                # outer_join uses compound op result
                compound_info[outer_join_name] = outer_foreach_name

        def _emit(node) -> None:
            if node.name in var_map:
                return
            # Ensure parents are emitted first
            for p in node.in_funcs:
                if p not in var_map and p not in steps_in_compound:
                    _emit(self.graph[p])

            # Skip steps handled inside compound ops
            if node.name in steps_in_compound:
                return

            op_call = self._op_name(node.name)
            ntype = node.type

            # ── start step ────────────────────────────────────────────────────
            if node.name == "start":
                var = "r_start"
                lines.append("%s = %s()" % (var, op_call))
                var_map["start"] = var
                if ntype == "split":
                    for branch in node.out_funcs:
                        var_map["_branch_%s" % branch] = "%s.%s" % (var, branch)
                elif ntype == "foreach" and "start" in chains and len(chains["start"]) > 1:
                    # Nested foreach: wire compound op via .map()
                    compound_name = self._compound_op_name("start")
                    compound_var = "r_start__body"
                    lines.append("%s = %s.map(%s)" % (compound_var, var, compound_name))
                    outer_body_name = chains["start"][0][1]
                    var_map[outer_body_name] = compound_var
                return

            # ── end step ──────────────────────────────────────────────────────
            if ntype == "end":
                pvar = self._resolve_input(node, var_map)
                lines.append("%s(%s)" % (op_call, pvar))
                var_map[node.name] = "_end"
                return

            # ── linear step ───────────────────────────────────────────────────
            if ntype == "linear":
                parent_is_foreach = any(
                    self.graph[p].type == "foreach"
                    or (p == "start" and self.graph["start"].type == "foreach")
                    for p in node.in_funcs
                )
                if parent_is_foreach:
                    foreach_parent = next(
                        p for p in node.in_funcs
                        if self.graph[p].type == "foreach"
                        or (p == "start" and self.graph["start"].type == "foreach")
                    )
                    # Check if this foreach_parent has a compound op (nested chain)
                    outer_foreach_name = foreach_parent
                    if outer_foreach_name in chains and len(chains[outer_foreach_name]) > 1:
                        # This body step is the first outer body (itself a foreach) —
                        # it should already be in steps_in_compound and thus skipped.
                        # If we get here something is wrong; emit a comment and skip.
                        var_map[node.name] = "None  # handled by compound op"
                        return
                    dyn_var = var_map[foreach_parent]
                    var = "r_%s" % node.name
                    lines.append("%s = %s.map(%s)" % (var, dyn_var, op_call))
                    var_map[node.name] = var
                else:
                    pvar = self._resolve_input(node, var_map)
                    var = "r_%s" % node.name
                    lines.append("%s = %s(%s)" % (var, op_call, pvar))
                    var_map[node.name] = var
                return

            # ── split step ────────────────────────────────────────────────────
            if ntype == "split":
                pvar = self._resolve_input(node, var_map)
                var = "r_%s" % node.name
                lines.append("%s = %s(%s)" % (var, op_call, pvar))
                var_map[node.name] = var
                for branch in node.out_funcs:
                    var_map["_branch_%s" % branch] = "%s.%s" % (var, branch)
                return

            # ── foreach step ──────────────────────────────────────────────────
            if ntype == "foreach":
                pvar = self._resolve_input(node, var_map)
                var = "r_%s" % node.name
                lines.append("%s = %s(%s)" % (var, op_call, pvar))
                var_map[node.name] = var
                # If this foreach has a nested chain, wire the compound op via .map()
                if node.name in chains and len(chains[node.name]) > 1:
                    compound_name = self._compound_op_name(node.name)
                    compound_var = "r_%s__body" % node.name
                    lines.append("%s = %s.map(%s)" % (compound_var, var, compound_name))
                    # The outer_join will use compound_var.collect(); store under outer_body name
                    outer_body_name = chains[node.name][0][1]
                    var_map[outer_body_name] = compound_var
                return

            # ── join step ─────────────────────────────────────────────────────
            if ntype == "join":
                is_foreach_join = bool(
                    node.split_parents
                    and (
                        self.graph[node.split_parents[-1]].type == "foreach"
                        or (
                            node.split_parents[-1] == "start"
                            and self.graph["start"].type == "foreach"
                        )
                    )
                )
                if is_foreach_join:
                    body_step = node.in_funcs[0]
                    if body_step in steps_in_compound:
                        # This is the outer join of a nested foreach chain.
                        # The compound op's mapped result is stored under the outer foreach's
                        # body step name (chain[0][1]) which is also the inner foreach name.
                        # node.split_parents[-1] is the outer foreach that feeds this join.
                        outer_foreach_name = node.split_parents[-1]
                        outer_body_name = chains[outer_foreach_name][0][1]
                        dyn_var = var_map.get(outer_body_name, "r_%s__body" % outer_foreach_name)
                    else:
                        dyn_var = var_map.get(body_step, "r_%s" % body_step)
                    var = "r_%s" % node.name
                    lines.append("%s = %s(%s.collect())" % (var, op_call, dyn_var))
                    var_map[node.name] = var
                else:
                    in_vars = [var_map.get(p, p) for p in node.in_funcs]
                    args = ", ".join(in_vars)
                    var = "r_%s" % node.name
                    lines.append("%s = %s(%s)" % (var, op_call, args))
                    var_map[node.name] = var
                return

        for node in self._topological_order():
            _emit(node)

        return "\n".join(lines) if lines else "pass"

    def _resolve_input(self, node, var_map: Dict[str, str]) -> str:
        """Get the Python expression for the first upstream input to this node."""
        parent = node.in_funcs[0] if node.in_funcs else None
        if parent is None:
            return "None"
        # Check if there's a named branch output for this step
        branch_key = f"_branch_{node.name}"
        if branch_key in var_map:
            return var_map[branch_key]
        return var_map.get(parent, parent)

    # ── Schedule ───────────────────────────────────────────────────────────────

    def _extract_schedule(self) -> Optional[str]:
        sched = self.flow._flow_decorators.get("schedule")
        if not sched:
            return None
        sched = sched[0]
        if sched.attributes.get("cron"):
            return sched.attributes["cron"]
        elif sched.attributes.get("daily"):
            return "0 0 * * *"
        elif sched.attributes.get("hourly"):
            return "0 * * * *"
        elif sched.attributes.get("weekly"):
            return "0 0 * * 0"
        return None

    def _render_schedule(self) -> str:
        return dedent(f"""\
            {self.job_name}_schedule = ScheduleDefinition(
                job={self.job_name},
                cron_schedule={self.schedule!r},
            )
        """)

    # ── Definitions ────────────────────────────────────────────────────────────

    def _render_definitions(self) -> str:
        sched_list = f"[{self.job_name}_schedule]" if self.schedule else "[]"
        return dedent(f"""\
            defs = Definitions(
                jobs=[{self.job_name}],
                schedules={sched_list},
            )
        """)

    # ── Utilities ──────────────────────────────────────────────────────────────

    def _tags_args_code(self) -> str:
        # Kept for backward compatibility with tests/imports; callers use repr(self.tags).
        return repr(self.tags)
