"""
DagsterCompiler: transforms a Metaflow FlowGraph into a Dagster definitions file.

Key insight: in Metaflow, the 'start' step is special by NAME, not by type.
Its graph type is determined by what self.next() does:
  - start → single next()    → type='start'
  - start → next(a, b)       → type='split'
  - start → next(a, foreach) → type='foreach'

Generated file structure:
  1. Preamble + imports
  2. Constants   (FLOW_FILE, METAFLOW_TOP_ARGS, METAFLOW_STEP_ENV)
  3. Helpers     (_make_run_id, _run_init, _run_step, _get_foreach_splits)
  4. Config      (Pydantic Config for flow parameters)
  5. Ops         (one @op per flow step)
  6. Job         (@job composing ops)
  7. Schedule    (optional)
  8. Sensors     (from @trigger / @trigger_on_finish, optional)
  9. Definitions
"""

import os
from collections import deque
from textwrap import dedent

from metaflow.decorators import flow_decorators
from metaflow.parameters import deploy_time_eval
from metaflow.util import dict_to_cli_options

# ──────────────────────────────────────────────────────────────────────────────
# Preamble template
# ──────────────────────────────────────────────────────────────────────────────

_PREAMBLE = '''\
"""
Dagster definitions generated by metaflow-dagster.
Flow   : {flow_name}
Job    : {job_name}
Source : {flow_file}

DO NOT EDIT — re-generate with:
    python {flow_basename} dagster create {output_file}
"""
import atexit
import hashlib
import json
import os
import subprocess
import sys
from typing import Dict, List, Optional

from dagster import (
    Config,
    DefaultSensorStatus,
    Definitions,
    DynamicOut,
    DynamicOutput,
    In,
    MetadataValue,
    OpExecutionContext,
    Out,
    Output,
    RetryPolicy,
    RunRequest,
    ScheduleDefinition,
    SensorDefinition,
    SensorEvaluationContext,
    job,
    op,
    sensor,
)
from metaflow.decorators import extract_step_decorator_from_decospec
from metaflow.util import compress_list

# ── Flow constants ─────────────────────────────────────────────────────────────
FLOW_FILE = {flow_file!r}
FLOW_NAME = {flow_name!r}

# When set, _run_step passes --clone-run-id to Metaflow so completed tasks are
# reused and only failed/pending steps are re-executed (resume support).
ORIGIN_RUN_ID: Optional[str] = {origin_run_id!r}

# Metaflow CLI top-level flags embedded at compile time
METAFLOW_TOP_ARGS: List[str] = {top_args!r}

# Metaflow env-vars forwarded to every subprocess
METAFLOW_STEP_ENV: Dict[str, str] = {step_env!r}

# Per-step runtime decorator specs and retry limits used to honor runtime_step_cli hooks.
STEP_DECORATOR_SPECS: Dict[str, List[str]] = {step_decorator_specs!r}
STEP_WITH_DECORATORS: Dict[str, List[str]] = {step_with_decorators!r}

# Per-step conda environment IDs, embedded at compile time.
# Maps step_name -> conda environment id_ (the sha256-based identifier used by
# Metaflow/Micromamba) or None if the step does not use a conda environment.
# Used by _get_conda_interpreter() to locate the correct Python interpreter.
STEP_CONDA_ENV_IDS: Dict[str, Optional[str]] = {step_conda_env_ids!r}


# ── Conda helpers ──────────────────────────────────────────────────────────────

_CONDA_BOOTSTRAP_DONE: bool = False
_CONDA_INTERP_CACHE: Dict[str, Optional[str]] = {{}}


def _bootstrap_conda_envs() -> None:
    """Bootstrap all conda environments for this flow by running \'package save\'.

    MetaflowPackage.__init__ calls environment.init_environment() which invokes
    micromamba to solve and install all step environments.  Running \'package save\'
    is the lightest-weight way to trigger that bootstrap without executing user code.
    """
    import tempfile
    with tempfile.NamedTemporaryFile(suffix=".tgz", delete=False) as tmp:
        pkg_path = tmp.name
    try:
        pkg_cmd = (
            [sys.executable, FLOW_FILE]
            + [a for a in METAFLOW_TOP_ARGS if a != "--quiet"]
            + ["package", "save", pkg_path]
        )
        proc = subprocess.Popen(
            pkg_cmd,
            env=_build_env(),
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            cwd=os.path.dirname(FLOW_FILE) or ".",
        )
        _communicate(proc)
        # Ignore errors — if bootstrap failed the step subprocess will
        # report a clear error; we do not want to mask it here.
    finally:
        try:
            os.unlink(pkg_path)
        except Exception:
            pass


def _get_conda_interpreter(step_name: str) -> Optional[str]:
    """Return the conda Python interpreter path for *step_name*, or None.

    On the first call (per Dagster process) all conda environments are bootstrapped
    via \'package save\' so that micromamba can resolve their on-disk paths.
    Subsequent calls reuse the cached result.
    """
    global _CONDA_BOOTSTRAP_DONE

    env_id = STEP_CONDA_ENV_IDS.get(step_name)
    if not env_id:
        return None

    if step_name in _CONDA_INTERP_CACHE:
        return _CONDA_INTERP_CACHE[step_name]

    if not _CONDA_BOOTSTRAP_DONE:
        _bootstrap_conda_envs()
        _CONDA_BOOTSTRAP_DONE = True

    interp: Optional[str] = None
    try:
        from metaflow.plugins.pypi.micromamba import Micromamba
        mm = Micromamba()
        env_path = mm.path_to_environment(env_id)
        if env_path:
            candidate = os.path.join(env_path, "bin", "python")
            if os.path.isfile(candidate):
                interp = candidate
    except Exception:
        pass

    _CONDA_INTERP_CACHE[step_name] = interp
    return interp


# ── Execution helpers ──────────────────────────────────────────────────────────

def _make_run_id(dagster_run_id: str) -> str:
    """Derive a short, deterministic Metaflow run-id from Dagster\'s UUID."""
    return "dagster-" + hashlib.sha1(dagster_run_id.encode()).hexdigest()[:12]


def _build_env(extra: Optional[Dict[str, str]] = None) -> Dict[str, str]:
    e = {{**os.environ, **METAFLOW_STEP_ENV}}
    if extra:
        e.update(extra)
    return e


def _communicate(proc: subprocess.Popen) -> tuple:
    """Wait for *proc* to finish, killing it cleanly on any interruption.

    If the calling thread is interrupted (op cancelled, timeout, SIGTERM),
    sends SIGTERM to the child and waits up to 10 s before escalating to
    SIGKILL, then re-raises so the op is marked failed rather than leaving
    the Metaflow subprocess as an orphan.
    """
    try:
        return proc.communicate()
    except BaseException:
        proc.terminate()
        try:
            proc.wait(timeout=10)
        except subprocess.TimeoutExpired:
            proc.kill()
            proc.wait()
        raise


def _run_cmd(
    context: OpExecutionContext,
    cmd: List[str],
    extra_env: Optional[Dict[str, str]] = None,
) -> None:
    context.log.info("$ " + " ".join(str(c) for c in cmd))
    proc = subprocess.Popen(
        cmd,
        env=_build_env(extra_env),
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        cwd=os.path.dirname(FLOW_FILE) or ".",
    )
    stdout, stderr = _communicate(proc)
    if stdout.strip():
        context.log.info(stdout)
    if stderr.strip():
        context.log.info(stderr)
    if proc.returncode != 0:
        raise RuntimeError(
            f"Command failed (exit {{proc.returncode}}):\\n{{stderr[-2000:]}}"
        )


def _run_init(
    context: OpExecutionContext,
    run_id: str,
    params_task_id: str,
    parameters: Optional[Dict] = None,
) -> str:
    """Create the _parameters task. Returns its full pathspec.

    Metaflow reads parameter overrides from METAFLOW_INIT_<NAME> env vars
    (not METAFLOW_PARAMETERS). Values must be raw strings — Metaflow applies
    its own type coercion when it reads the parameter from the _parameters task.
    """
    cmd = (
        [sys.executable, FLOW_FILE]
        + METAFLOW_TOP_ARGS
        + ["init", "--run-id", run_id, "--task-id", params_task_id]
    )
    if ORIGIN_RUN_ID:
        cmd += ["--clone-run-id", ORIGIN_RUN_ID]
    extra = {{
        "METAFLOW_INIT_" + k.upper().replace("-", "_"): str(v)
        for k, v in (parameters or {{}}).items()
    }}
    _run_cmd(context, cmd, extra or None)
    return f"{{run_id}}/_parameters/{{params_task_id}}"


def _get_ds_root() -> str:
    """Return the local datastore root from embedded top-level args or env."""
    return next(
        (a.split("--datastore-root=", 1)[1] for a in METAFLOW_TOP_ARGS if a.startswith("--datastore-root=")),
        os.environ.get("METAFLOW_DATASTORE_SYSROOT_LOCAL", ""),
    )


# Code package cache — built once per process when @sandbox (or similar) is present.
# The tarball is kept on disk until process exit so TarballStager can deliver it.
_CODE_PACKAGE_CACHE: Dict[str, Optional[str]] = {{
    "metadata": None, "sha": None, "url": None, "local_path": None,
}}


def _ensure_code_package():
    """Build and upload the flow code package, caching the result process-wide."""
    if _CODE_PACKAGE_CACHE["metadata"] is not None:
        return (
            _CODE_PACKAGE_CACHE["metadata"],
            _CODE_PACKAGE_CACHE["sha"],
            _CODE_PACKAGE_CACHE["url"],
            _CODE_PACKAGE_CACHE["local_path"],
        )

    import re
    import tempfile
    from metaflow.datastore import FlowDataStore
    from metaflow.plugins import DATASTORES

    with tempfile.NamedTemporaryFile(suffix=".tgz", delete=False) as tmp:
        package_path = tmp.name
    try:
        package_cmd = (
            [sys.executable, FLOW_FILE]
            + [a for a in METAFLOW_TOP_ARGS if a != "--quiet"]
            + ["package", "save", package_path]
        )
        _pkg_proc = subprocess.Popen(
            package_cmd,
            env=_build_env(),
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            cwd=os.path.dirname(FLOW_FILE) or ".",
        )
        _pkg_stdout, _pkg_stderr = _communicate(_pkg_proc)
        if _pkg_proc.returncode != 0:
            raise RuntimeError(
                "Failed to build Metaflow code package:\\n"
                + (_pkg_stderr or _pkg_stdout)[-2000:]
            )
        meta_src = (_pkg_stdout or "") + "\\n" + (_pkg_stderr or "")
        m = re.search(r"metadata:\\s*(\\{{.*\\}})", meta_src)
        package_metadata = (
            m.group(1).strip()
            if m
            else '{{"version": 0, "archive_format": "tgz", "mfcontent_version": 1}}'
        )

        with open(package_path, "rb") as f:
            blob = f.read()

        datastore_type = next(
            (a.split("--datastore=", 1)[1] for a in METAFLOW_TOP_ARGS if a.startswith("--datastore=")),
            None,
        )
        storage_impl = next(ds for ds in DATASTORES if ds.TYPE == datastore_type)
        flow_datastore = FlowDataStore(
            FLOW_NAME,
            storage_impl=storage_impl,
            ds_root=_get_ds_root() or None,
        )
        package_url, package_sha = flow_datastore.save_data([blob], len_hint=1)[0]
        _CODE_PACKAGE_CACHE["metadata"] = package_metadata
        _CODE_PACKAGE_CACHE["sha"] = package_sha
        _CODE_PACKAGE_CACHE["url"] = package_url
        _CODE_PACKAGE_CACHE["local_path"] = package_path
        atexit.register(lambda p=package_path: os.path.exists(p) and os.unlink(p))
    except Exception:
        try:
            os.unlink(package_path)
        except Exception:
            pass
        raise

    return (
        _CODE_PACKAGE_CACHE["metadata"],
        _CODE_PACKAGE_CACHE["sha"],
        _CODE_PACKAGE_CACHE["url"],
        _CODE_PACKAGE_CACHE["local_path"],
    )


def _run_step(
    context: OpExecutionContext,
    step_name: str,
    run_id: str,
    input_paths: str,
    task_id: str,
    retry_count: int = 0,
    max_user_code_retries: int = 0,
    tags: Optional[List[str]] = None,
    split_index: Optional[int] = None,
    extra_env: Optional[Dict[str, str]] = None,
) -> str:
    """Execute one Metaflow step. Returns its full task pathspec."""
    class _CLIArgs:
        def __init__(self):
            self.entrypoint = [sys.executable, FLOW_FILE]
            self.top_level_args = list(METAFLOW_TOP_ARGS) + [
                f"--with={{d}}" for d in STEP_WITH_DECORATORS.get(step_name, [])
            ]
            self.commands = ["step"]
            self.command_args = [step_name]
            self.command_options = {{
                "run-id": run_id,
                "task-id": task_id,
                "input-paths": input_paths,
                "retry-count": retry_count,
                "max-user-code-retries": max_user_code_retries,
                "tag": tags or [],
                "namespace": next(
                    (
                        a.split("--namespace=", 1)[1]
                        for a in METAFLOW_TOP_ARGS
                        if a.startswith("--namespace=")
                    ),
                    None,
                ),
            }}
            if ORIGIN_RUN_ID:
                self.command_options["clone-run-id"] = ORIGIN_RUN_ID
            if split_index is not None:
                self.command_options["split-index"] = split_index
            self.env: Dict[str, str] = {{}}

        def _options(self, mapping):
            for k, v in mapping.items():
                if v is None or v is False:
                    continue
                if k == "decospecs":
                    k = "with"
                k = k.replace("_", "-")
                vals = v if isinstance(v, (list, tuple, set)) else [v]
                for value in vals:
                    yield f"--{{k}}"
                    if not isinstance(value, bool):
                        if isinstance(value, tuple):
                            for vv in value:
                                yield str(vv)
                        else:
                            yield str(value)

        def get_args(self):
            args = list(self.entrypoint)
            args.extend(self.top_level_args)
            args.extend(self.commands)
            args.extend(
                str(arg) if arg is not None else "" for arg in self.command_args
            )
            args.extend(self._options(self.command_options))
            return args

    cli_args = _CLIArgs()

    for spec in STEP_DECORATOR_SPECS.get(step_name, []):
        deco, _ = extract_step_decorator_from_decospec(spec)
        # Set instance attributes that step_init would normally provide.
        # runtime_step_cli (e.g. SandboxDecorator) accesses _step_name for dep staging.
        if not hasattr(deco, "_step_name"):
            deco._step_name = step_name
        if (
            hasattr(deco, "package_metadata")
            and deco.package_metadata is None
            and hasattr(deco, "package_sha")
            and hasattr(deco, "package_url")
        ):
            package_metadata, package_sha, package_url, package_local_path = _ensure_code_package()
            deco.package_metadata = package_metadata
            deco.package_sha = package_sha
            deco.package_url = package_url
            # Propagate to the defining class so TarballStager delivery works for @sandbox.
            # Traverse MRO to find the class that declares package_local_path (e.g.
            # SandboxDecorator), not a subclass that merely inherits it.
            if package_local_path:
                for _cls in type(deco).__mro__:
                    if "package_local_path" in _cls.__dict__:
                        _cls.package_local_path = package_local_path
                        break
        deco.runtime_step_cli(cli_args, retry_count, max_user_code_retries, None)

    # If this step runs inside a conda environment, replace the Python entrypoint
    # with the conda env\'s interpreter.  This is what runtime_step_cli does in
    # the normal Metaflow runtime (after runtime_task_created sets self.interpreter),
    # but Dagster bypasses the runtime hooks so we replicate the logic here.
    conda_interp = _get_conda_interpreter(step_name)
    if conda_interp:
        cli_args.entrypoint[0] = conda_interp
        cli_args.env["PYTHONNOUSERSITE"] = "1"

    cmd = cli_args.get_args()
    merged_env = dict(cli_args.env)
    if extra_env:
        merged_env.update(extra_env)
    _run_cmd(context, cmd, merged_env or None)
    return f"{{run_id}}/{{step_name}}/{{task_id}}"


def _get_foreach_splits(run_id: str, step_name: str, task_id: str) -> int:
    """Read the foreach cardinality via the FlowDataStore API.

    Uses the proper datastore abstraction instead of manually navigating
    the local file layout and deserializing pickle blobs.
    """
    from metaflow.datastore import FlowDataStore
    from metaflow.plugins import DATASTORES

    ds_type = next(
        (a.split("=", 1)[1] for a in METAFLOW_TOP_ARGS if a.startswith("--datastore=")),
        next(
            (a for i, a in enumerate(METAFLOW_TOP_ARGS) if i > 0 and METAFLOW_TOP_ARGS[i - 1] == "--datastore"),
            "local",
        ),
    )
    try:
        _impl = next(d for d in DATASTORES if d.TYPE == ds_type)
        _root = _impl.get_datastore_root_from_config(lambda *a: None)
        _fds = FlowDataStore(FLOW_NAME, None, storage_impl=_impl, ds_root=_root)
        _tds = _fds.get_task_datastore(run_id, step_name, task_id, attempt=0, mode='r')
        return int(_tds['_foreach_num_splits'])
    except Exception as exc:
        raise RuntimeError(
            f"Could not read foreach splits for {{step_name!r}}: {{exc}}"
        ) from exc


def _get_condition_branch(run_id: str, step_name: str, task_id: str) -> str:
    """Read the condition branch taken via the FlowDataStore API.

    Uses the proper datastore abstraction instead of manually navigating
    the local file layout and deserializing pickle blobs.
    """
    from metaflow.datastore import FlowDataStore
    from metaflow.plugins import DATASTORES

    ds_type = next(
        (a.split("=", 1)[1] for a in METAFLOW_TOP_ARGS if a.startswith("--datastore=")),
        next(
            (a for i, a in enumerate(METAFLOW_TOP_ARGS) if i > 0 and METAFLOW_TOP_ARGS[i - 1] == "--datastore"),
            "local",
        ),
    )
    try:
        _impl = next(d for d in DATASTORES if d.TYPE == ds_type)
        _root = _impl.get_datastore_root_from_config(lambda *a: None)
        _fds = FlowDataStore(FLOW_NAME, None, storage_impl=_impl, ds_root=_root)
        _tds = _fds.get_task_datastore(run_id, step_name, task_id, attempt=0, mode='r')
        _transition = _tds['_transition']
        if isinstance(_transition, (list, tuple)) and _transition:
            return str(_transition[0])
        return str(_transition)
    except Exception as exc:
        raise RuntimeError(
            f"Could not read condition branch for {{step_name!r}}: {{exc}}"
        ) from exc


def _add_step_metadata(
    context: OpExecutionContext,
    task_path: str,
    output_name: Optional[str] = None,
) -> None:
    """Emit artifact-key metadata to the Dagster UI.

    Reads the 0.data.json index from the local datastore so Dagster can show
    which Metaflow artifact keys exist for this step. Does NOT load artifact
    values — they remain in the Metaflow datastore. Also emits a Python
    snippet showing how to retrieve each artifact via the Metaflow Task API.
    """
    parts = task_path.split("/")
    if len(parts) < 3:
        return
    run_id, step_name, task_id = parts[0], parts[1], parts[2]
    data_json_path = os.path.join(
        _get_ds_root(), FLOW_NAME, run_id, step_name, task_id, "0.data.json"
    )
    try:
        with open(data_json_path) as fh:
            objects = json.load(fh).get("objects", {{}})
    except Exception as _exc:
        context.log.warning("Could not read artifact metadata for %s: %s" % (task_path, _exc))
        return
    keys = [k for k in objects if not k.startswith("_")]
    if not keys:
        return
    pathspec = "/".join([FLOW_NAME, run_id, step_name, task_id])
    lines = ["from metaflow import Task", "task = Task(" + repr(pathspec) + ")"]
    lines += ["task[" + repr(k) + "].data  # " + k for k in keys]
    snippet = "\\n".join(lines)
    meta = {{
        "artifact_keys": MetadataValue.md(
            "**Metaflow artifacts:** " + ", ".join("`" + k + "`" for k in keys)
        ),
        "retrieve (copy ↓)": MetadataValue.text(snippet),
    }}
    kwargs = {{"output_name": output_name}} if output_name is not None else {{}}
    try:
        context.add_output_metadata(meta, **kwargs)
    except Exception as _exc:
        context.log.warning("Could not attach output metadata for %s: %s" % (task_path, _exc))


'''


# ──────────────────────────────────────────────────────────────────────────────
# Compiler
# ──────────────────────────────────────────────────────────────────────────────

class DagsterCompiler:
    # Loop index variable names used inside compound op bodies (one per nesting level)
    _LOOP_IDX = ["_i", "_j", "_k", "_l", "_m"]

    def __init__(
        self,
        job_name: str,
        graph,
        flow,
        flow_file: str,
        metadata,
        environment,
        flow_datastore,
        event_logger,
        monitor,
        tags: list[str],
        with_decorators: list[str],
        namespace: str | None,
        workflow_timeout: int | None,
        step_env: dict[str, str],
        origin_run_id: str | None = None,
    ):
        self.job_name = job_name
        self.graph = graph
        self.flow = flow
        self.flow_file = flow_file
        self.metadata = metadata
        self.environment = environment
        self.flow_datastore = flow_datastore
        self.event_logger = event_logger
        self.monitor = monitor
        self.tags = tags
        self.with_decorators = with_decorators
        self.namespace = namespace
        self.workflow_timeout = workflow_timeout
        self.step_env = step_env
        self.origin_run_id = origin_run_id

        self.flow_name = flow.name
        self.parameters = self._extract_parameters()
        self.schedule = self._extract_schedule()
        self.triggers = self._extract_triggers()
        self.trigger_on_finishes = self._extract_trigger_on_finishes()

        self._topo_cache: list | None = None
        self._foreach_chains_cache: dict[str, list] | None = None

    # ── Public ─────────────────────────────────────────────────────────────────

    def compile(self) -> str:
        parts = [self._render_preamble()]
        config = self._render_config_class()
        if config:
            parts.append(config)
        chains = self._foreach_chains()
        steps_in_compound = self._steps_in_compound()
        for node in self._topological_order():
            if node.name not in steps_in_compound:
                parts.append(self._render_op(node))
        # Emit compound ops for any nested foreach chains
        for chain in chains.values():
            if len(chain) > 1:
                parts.append(self._render_nested_foreach_compound_op(chain))
        parts.append(self._render_job())
        if self.schedule:
            parts.append(self._render_schedule())
        for sensor_code in self._render_sensors():
            parts.append(sensor_code)
        parts.append(self._render_definitions())
        return "\n\n".join(p for p in parts if p.strip()) + "\n"

    # ── Preamble ───────────────────────────────────────────────────────────────

    def _render_preamble(self) -> str:
        step_decorator_specs, step_with_decorators = self._build_step_decorator_info()
        return _PREAMBLE.format(
            flow_name=self.flow_name,
            job_name=self.job_name,
            flow_file=self.flow_file,
            flow_basename=os.path.basename(self.flow_file),
            output_file="<output.py>",
            top_args=self._build_top_args(),
            step_env=self.step_env,
            step_decorator_specs=step_decorator_specs,
            step_with_decorators=step_with_decorators,
            step_conda_env_ids=self._build_step_conda_env_ids(),
            origin_run_id=self.origin_run_id,
        )

    def _build_top_args(self) -> list[str]:
        top_opts_dict: dict = {}
        for deco in flow_decorators(self.flow):
            top_opts_dict.update(deco.get_top_level_options())
        top_opts = list(dict_to_cli_options(top_opts_dict))
        args = top_opts + [
            "--quiet",
            "--no-pylint",
            f"--metadata={self.metadata.TYPE}",
            f"--environment={self.environment.TYPE}",
            f"--datastore={self.flow_datastore.TYPE}",
            f"--datastore-root={self.flow_datastore.datastore_root}",
            f"--event-logger={self.event_logger.TYPE}",
            f"--monitor={self.monitor.TYPE}",
        ]
        if self.namespace:
            args.append(f"--namespace={self.namespace}")
        return args

    def _build_step_decorator_info(self) -> "tuple[dict[str, list[str]], dict[str, list[str]]]":
        """Return (decorator_specs, with_decorators) dicts in a single pass over the graph.

        For steps that carry @resources, the resource hints are forwarded to the
        Metaflow compute backend via an extra resources:cpu=N,memory=M,gpu=G entry
        in STEP_WITH_DECORATORS so backends like @kubernetes pick them up.
        """
        specs: dict[str, list[str]] = {}
        withs: dict[str, list[str]] = {}
        for node in self._topological_order():
            step_specs = [d.make_decorator_spec() for d in node.decorators]
            step_specs.extend(self.with_decorators)
            specs[node.name] = step_specs
            step_withs = list(self.with_decorators)
            # Forward @resources hints so compute backends receive them
            resources_spec = self._build_resources_spec(node)
            if resources_spec:
                step_withs.append(resources_spec)
            withs[node.name] = step_withs
        return specs, withs

    def _build_step_conda_env_ids(self) -> "dict[str, str | None]":
        """Return a mapping of step_name -> conda environment id_ (or None).

        The id_ is the short SHA256 hash that Metaflow/Micromamba uses to identify
        a solved conda environment.  It is computed deterministically from the step's
        @conda decorator attributes (packages, python version, pinned libs, etc.).

        This information is embedded in the generated file so that, at runtime,
        _get_conda_interpreter() can locate the correct Python binary without having
        to re-parse the flow or re-instantiate the environment object.

        Returns an empty dict (all Nones) when the environment is not conda-based,
        preventing any conda-specific logic from running for non-conda deployments.
        """
        result: dict[str, str | None] = {}
        # Only applicable for conda-family environments
        if not hasattr(self.environment, "get_environment"):
            for node in self._topological_order():
                result[node.name] = None
            return result
        for node in self._topological_order():
            try:
                env_info = self.environment.get_environment(node)
                id_ = env_info.get("id_")
                # Ensure the id_ is a plain string, not a mock object or other type.
                result[node.name] = id_ if isinstance(id_, str) and id_ else None
            except Exception:
                result[node.name] = None
        return result

    def _build_resources_spec(self, node) -> str | None:
        """Return a 'resources:cpu=N,memory=M,gpu=G' spec string from @resources, or None."""
        for deco in node.decorators:
            if deco.name == "resources":
                parts = []
                cpu = deco.attributes.get("cpu")
                memory = deco.attributes.get("memory")
                gpu = deco.attributes.get("gpu")
                if cpu is not None:
                    parts.append(f"cpu={cpu}")
                if memory is not None:
                    parts.append(f"memory={memory}")
                if gpu is not None:
                    parts.append(f"gpu={gpu}")
                if parts:
                    return "resources:" + ",".join(parts)
        return None

    # ── Config class ───────────────────────────────────────────────────────────

    def _extract_parameters(self) -> list[dict]:
        params = []
        for _, param in self.flow._get_parameters():
            default = deploy_time_eval(param.kwargs.get("default"))
            params.append({
                "name": param.name,
                "default": default,
                "help": param.kwargs.get("help", ""),
                "type": type(default).__name__ if default is not None else "str",
            })
        return params

    def _render_config_class(self) -> str:
        if not self.parameters:
            return ""
        lines = [f"class {self.flow_name}Config(Config):"]
        for p in self.parameters:
            default = p["default"]
            ann = p["type"]  # "bool", "int", "float", or "str"
            val = default if ann != "str" else (str(default) if default is not None else "")
            comment = f"  # {p['help']}" if p["help"] else ""
            lines.append(f"    {p['name']}: {ann} = {val!r}{comment}")
        return "\n".join(lines)

    # ── Op rendering ───────────────────────────────────────────────────────────

    def _steps_in_compound(self) -> set:
        """Return step names that are handled inside compound ops.

        Steps in this set must NOT be emitted as standalone @op definitions,
        nor visited in the top-level job body — they are fully contained
        inside the compound op generated for each nested foreach chain.
        """
        result = set()
        for chain in self._foreach_chains().values():
            if len(chain) > 1:
                result.add(chain[0][1])  # outer_body (itself a foreach step)
                for _, body_n, join_n in chain[1:]:
                    result.add(body_n)
                    result.add(join_n)
        return result

    def _topological_order(self):
        if self._topo_cache is None:
            visited = set()
            queue = deque([self.graph["start"]])
            result = []
            while queue:
                node = queue.popleft()
                if node.name in visited:
                    continue
                visited.add(node.name)
                result.append(node)
                for child in node.out_funcs:
                    queue.append(self.graph[child])
            self._topo_cache = result
        return self._topo_cache

    def _op_name(self, step_name: str) -> str:
        return f"op_{step_name}"

    def _ins_spec(self, name: str, type_: str = "str") -> str:
        """Return the Dagster ins= dict literal string for a single named input."""
        return f'{{"{name}": In({type_})}}'

    def _is_foreach_join(self, node) -> bool:
        """Return True if *node* is a join that collects dynamic foreach outputs."""
        split_parent = node.split_parents[-1] if node.split_parents else None
        return split_parent is not None and self.graph[split_parent].type == "foreach"

    def _is_condition_branch(self, node) -> bool:
        """Return True if *node* is a linear branch step of a split-switch."""
        return (
            len(node.in_funcs) == 1
            and self.graph[node.in_funcs[0]].type == "split-switch"
        )

    def _is_condition_merge(self, node) -> bool:
        """Return True if *node* is the merge step that follows a split-switch."""
        if len(node.in_funcs) < 2:
            return False
        parent_sets = [set(self.graph[p].in_funcs) for p in node.in_funcs]
        common: set[str] = parent_sets[0].copy()
        for s in parent_sets[1:]:
            common &= s
        return any(self.graph[p].type == "split-switch" for p in common)

    def _condition_switch_name(self, node) -> str:
        """Return the split-switch step name that this condition merge closes."""
        parent_sets = [set(self.graph[p].in_funcs) for p in node.in_funcs]
        common: set[str] = parent_sets[0].copy()
        for s in parent_sets[1:]:
            common &= s
        return next(p for p in common if self.graph[p].type == "split-switch")

    def _render_op(self, node) -> str:
        # The "start" step is special regardless of its graph type
        if node.name == "start":
            return self._render_start_op(node)
        ntype = node.type
        if ntype == "end":
            return self._render_end_op(node)
        elif ntype == "linear":
            return self._render_linear_op(node)
        elif ntype == "join":
            return self._render_join_op(node)
        elif ntype == "split":
            return self._render_split_op(node)
        elif ntype == "foreach":
            return self._render_foreach_op(node)
        elif ntype == "split-switch":
            return self._render_split_switch_op(node)
        else:
            raise NotImplementedError(f"Unsupported node type: {ntype!r} for step {node.name!r}")

    # ── Per-step decorator helpers ─────────────────────────────────────────────

    def _get_retry_info(self, node):
        """Returns (max_retries, delay_seconds_or_None) from @retry decorator."""
        max_retries = 0
        delay_seconds = None
        for deco in node.decorators:
            try:
                user_retries, _ = deco.step_task_retry_count()
                max_retries = max(max_retries, user_retries)
            except Exception:
                pass
            if deco.name == "retry" and delay_seconds is None:
                mins = deco.attributes.get("minutes_between_retries", 0)
                if mins:
                    delay_seconds = int(mins) * 60
        return max_retries, delay_seconds

    def _get_timeout_seconds(self, node) -> int | None:
        """Returns timeout in seconds from @timeout decorator, or None."""
        for deco in node.decorators:
            if deco.name == "timeout":
                secs = int(deco.attributes.get("seconds") or 0)
                mins = int(deco.attributes.get("minutes") or 0)
                hours = int(deco.attributes.get("hours") or 0)
                total = secs + mins * 60 + hours * 3600
                if total > 0:
                    return total
        return None

    def _get_env_vars(self, node) -> dict[str, str]:
        """Returns env vars dict from @environment decorator."""
        for deco in node.decorators:
            if deco.name == "environment":
                return deco.attributes.get("vars") or {}
        return {}

    def _op_decorator_str(self, node, ins_spec: str = "", out_spec: str = "") -> str:
        """Build '@op(...)' string, including retry_policy and tags if applicable."""
        max_retries, delay_seconds = self._get_retry_info(node)
        timeout_seconds = self._get_timeout_seconds(node)

        parts = []
        if ins_spec:
            parts.append(f"ins={ins_spec}")
        if out_spec:
            parts.append(f"out={out_spec}")
        if max_retries > 0:
            if delay_seconds:
                parts.append(f"retry_policy=RetryPolicy(max_retries={max_retries}, delay={delay_seconds})")
            else:
                parts.append(f"retry_policy=RetryPolicy(max_retries={max_retries})")
        if timeout_seconds:
            parts.append(f'tags={{"dagster/op_execution_timeout": "{timeout_seconds}"}}')
        return f"@op({', '.join(parts)})"

    def _extra_env_code(self, node) -> str:
        """Returns a Python dict literal for @environment vars, or 'None'."""
        env_vars = self._get_env_vars(node)
        return repr(env_vars) if env_vars else "None"

    # start op (handles any start type) ───────────────────────────────────────

    def _render_start_op(self, node) -> str:
        """The start step always runs init+step; outputs depend on its graph type."""
        ntype = node.type  # 'start', 'split', or 'foreach'
        config_ann = f", config: {self.flow_name}Config" if self.parameters else ""
        param_dict = (
            "{" + ", ".join(f'"{p["name"]}": config.{p["name"]}' for p in self.parameters) + "}"
            if self.parameters else "{}"
        )
        tags_code = repr(self.tags)
        env_code = self._extra_env_code(node)
        max_retries, _ = self._get_retry_info(node)

        # The common body: init then step
        common = (
            f'    run_id = _make_run_id(context.run_id)\n'
            f'    parameters = {param_dict}\n'
            f'    params_path = _run_init(context, run_id, "params", parameters)\n'
            f'    task_path = _run_step(\n'
            f'        context, "start", run_id, params_path, "1",\n'
            f'        retry_count=context.retry_number,\n'
            f'        max_user_code_retries={max_retries},\n'
            f'        tags={tags_code},\n'
            f'        extra_env={env_code},\n'
            f'    )\n'
        )

        op_name = self._op_name("start")
        if ntype == "start":
            deco = self._op_decorator_str(node, out_spec="Out(str)")
            return (
                f'{deco}\n'
                f'def {op_name}(context: OpExecutionContext{config_ann}) -> str:\n'
                + common
                + '    _add_step_metadata(context, task_path)\n'
                + '    return task_path\n'
            )
        elif ntype == "split":
            branches = node.out_funcs
            first_branch = branches[0]
            out_spec = "{" + ", ".join(f'"{b}": Out(str)' for b in branches) + "}"
            deco = self._op_decorator_str(node, out_spec=out_spec)
            yields = "".join(
                f'    yield Output(task_path, output_name="{b}")\n' for b in branches
            )
            return (
                f'{deco}\n'
                f'def {op_name}(context: OpExecutionContext{config_ann}):\n'
                + common
                + f'    _add_step_metadata(context, task_path, output_name="{first_branch}")\n'
                + yields
            )
        elif ntype == "foreach":
            deco = self._op_decorator_str(node, out_spec="DynamicOut(str)")
            return (
                f'{deco}\n'
                f'def {op_name}(context: OpExecutionContext{config_ann}):\n'
                + common
                + '    _add_step_metadata(context, task_path)\n'
                + '    num_splits = _get_foreach_splits(run_id, "start", "1")\n'
                + '    for _i in range(num_splits):\n'
                + '        yield DynamicOutput(f"{task_path}//_i={_i}", mapping_key=str(_i))\n'
            )
        elif ntype == "split-switch":
            branches = node.out_funcs
            out_spec = "{" + ", ".join(f'"{b}": Out(str, is_required=False)' for b in branches) + "}"
            deco = self._op_decorator_str(node, out_spec=out_spec)
            return (
                f'{deco}\n'
                f'def {op_name}(context: OpExecutionContext{config_ann}):\n'
                + common
                + '    _add_step_metadata(context, task_path)\n'
                + '    _branch = _get_condition_branch(run_id, "start", "1")\n'
                + '    yield Output(task_path, output_name=_branch)\n'
            )
        else:
            raise NotImplementedError(f"start step with type {ntype!r}")

    # end op ───────────────────────────────────────────────────────────────────

    def _render_end_op(self, node) -> str:
        in_name = node.in_funcs[0] if node.in_funcs else "upstream"
        tags = repr(self.tags)
        env_code = self._extra_env_code(node)
        max_retries, _ = self._get_retry_info(node)
        ins_spec = self._ins_spec(in_name)
        deco = self._op_decorator_str(node, ins_spec=ins_spec)
        return dedent(f"""\
            {deco}
            def {self._op_name(node.name)}(context: OpExecutionContext, {in_name}: str) -> None:
                run_id = {in_name}.split("/")[0]
                _run_step(context, "{node.name}", run_id, {in_name}, "1",
                    retry_count=context.retry_number, max_user_code_retries={max_retries},
                    tags={tags}, extra_env={env_code})
        """)

    # linear op ────────────────────────────────────────────────────────────────

    def _render_linear_op(self, node) -> str:
        if self._is_condition_merge(node):
            return self._render_condition_merge_op(node)
        parent_is_foreach = any(self.graph[p].type == "foreach" for p in node.in_funcs)
        in_name = node.in_funcs[0] if node.in_funcs else "upstream"
        tags = repr(self.tags)
        env_code = self._extra_env_code(node)
        max_retries, _ = self._get_retry_info(node)
        ins_spec = self._ins_spec(in_name)
        deco = self._op_decorator_str(node, ins_spec=ins_spec, out_spec="Out(str)")

        if parent_is_foreach:
            # Body step of a foreach: receives encoded task_path + split index
            return dedent(f"""\
                {deco}
                def {self._op_name(node.name)}(context: OpExecutionContext, {in_name}: str) -> str:
                    # {in_name} = "run_id/step/task_id//_i=N"
                    parts = {in_name}.split("//_i=")
                    base_path, split_index = parts[0], int(parts[1]) if len(parts) > 1 else 0
                    run_id = base_path.split("/")[0]
                    task_id = f"1-{{split_index}}"
                    task_path = _run_step(
                        context, "{node.name}", run_id, base_path, task_id,
                        retry_count=context.retry_number,
                        max_user_code_retries={max_retries},
                        tags={tags},
                        split_index=split_index,
                        extra_env={env_code},
                    )
                    _add_step_metadata(context, task_path)
                    return task_path
            """)
        else:
            return dedent(f"""\
                {deco}
                def {self._op_name(node.name)}(context: OpExecutionContext, {in_name}: str) -> str:
                    run_id = {in_name}.split("/")[0]
                    task_path = _run_step(context, "{node.name}", run_id, {in_name}, "1",
                        retry_count=context.retry_number, max_user_code_retries={max_retries},
                        tags={tags}, extra_env={env_code})
                    _add_step_metadata(context, task_path)
                    return task_path
            """)

    # split op ─────────────────────────────────────────────────────────────────

    def _render_split_op(self, node) -> str:
        in_name = node.in_funcs[0] if node.in_funcs else "upstream"
        branches = node.out_funcs
        first_branch = branches[0]
        out_spec = "{" + ", ".join(f'"{b}": Out(str)' for b in branches) + "}"
        ins_spec = self._ins_spec(in_name)
        tags = repr(self.tags)
        env_code = self._extra_env_code(node)
        max_retries, _ = self._get_retry_info(node)
        deco = self._op_decorator_str(node, ins_spec=ins_spec, out_spec=out_spec)
        yields = "\n    ".join(
            f'yield Output(task_path, output_name="{b}")' for b in branches
        )
        return dedent(f"""\
            {deco}
            def {self._op_name(node.name)}(context: OpExecutionContext, {in_name}: str):
                run_id = {in_name}.split("/")[0]
                task_path = _run_step(context, "{node.name}", run_id, {in_name}, "1",
                    retry_count=context.retry_number, max_user_code_retries={max_retries},
                    tags={tags}, extra_env={env_code})
                _add_step_metadata(context, task_path, output_name="{first_branch}")
                {yields}
        """)

    # join op ──────────────────────────────────────────────────────────────────

    def _render_join_op(self, node) -> str:
        is_foreach_join = self._is_foreach_join(node)
        tags = repr(self.tags)
        env_code = self._extra_env_code(node)
        max_retries, _ = self._get_retry_info(node)

        if is_foreach_join:
            in_name = "foreach_results"
            ins_spec = self._ins_spec("foreach_results", "list")
            deco = self._op_decorator_str(node, ins_spec=ins_spec, out_spec="Out(str)")
            return dedent(f"""\
                {deco}
                def {self._op_name(node.name)}(context: OpExecutionContext, {in_name}: list) -> str:
                    run_id = {in_name}[0].split("/")[0]
                    clean = [p.split("//_i=")[0] for p in {in_name}]
                    input_paths = compress_list(clean)
                    task_path = _run_step(context, "{node.name}", run_id, input_paths, "1",
                        retry_count=context.retry_number, max_user_code_retries={max_retries},
                        tags={tags}, extra_env={env_code})
                    _add_step_metadata(context, task_path)
                    return task_path
            """)
        else:
            # Regular split-join: receives one input per branch
            ins_parts = [f'"{p}": In(str)' for p in node.in_funcs]
            ins_spec = "{" + ", ".join(ins_parts) + "}"
            args = ", ".join(node.in_funcs)
            paths_list = "[" + ", ".join(node.in_funcs) + "]"
            deco = self._op_decorator_str(node, ins_spec=ins_spec, out_spec="Out(str)")
            return dedent(f"""\
                {deco}
                def {self._op_name(node.name)}(context: OpExecutionContext, {args}) -> str:
                    run_id = {node.in_funcs[0]}.split("/")[0]
                    input_paths = compress_list({paths_list})
                    task_path = _run_step(context, "{node.name}", run_id, input_paths, "1",
                        retry_count=context.retry_number, max_user_code_retries={max_retries},
                        tags={tags}, extra_env={env_code})
                    _add_step_metadata(context, task_path)
                    return task_path
            """)

    # foreach op ───────────────────────────────────────────────────────────────

    def _render_foreach_op(self, node) -> str:
        in_name = node.in_funcs[0] if node.in_funcs else "upstream"
        tags = repr(self.tags)
        env_code = self._extra_env_code(node)
        max_retries, _ = self._get_retry_info(node)
        ins_spec = self._ins_spec(in_name)
        deco = self._op_decorator_str(node, ins_spec=ins_spec, out_spec="DynamicOut(str)")
        return dedent(f"""\
            {deco}
            def {self._op_name(node.name)}(context: OpExecutionContext, {in_name}: str):
                run_id = {in_name}.split("/")[0]
                task_path = _run_step(context, "{node.name}", run_id, {in_name}, "1",
                    retry_count=context.retry_number, max_user_code_retries={max_retries},
                    tags={tags}, extra_env={env_code})
                _add_step_metadata(context, task_path)
                num_splits = _get_foreach_splits(run_id, "{node.name}", "1")
                for _i in range(num_splits):
                    yield DynamicOutput(f"{{task_path}}//_i={{_i}}", mapping_key=str(_i))
        """)

    # split-switch op ──────────────────────────────────────────────────────────

    def _render_split_switch_op(self, node) -> str:
        """Generate @op for a mid-flow split-switch (conditional) step."""
        in_name = node.in_funcs[0] if node.in_funcs else "upstream"
        branches = node.out_funcs
        out_spec = "{" + ", ".join(f'"{b}": Out(str, is_required=False)' for b in branches) + "}"
        ins_spec = self._ins_spec(in_name)
        tags = repr(self.tags)
        env_code = self._extra_env_code(node)
        max_retries, _ = self._get_retry_info(node)
        deco = self._op_decorator_str(node, ins_spec=ins_spec, out_spec=out_spec)
        return dedent(f"""\
            {deco}
            def {self._op_name(node.name)}(context: OpExecutionContext, {in_name}: str):
                run_id = {in_name}.split("/")[0]
                task_path = _run_step(context, "{node.name}", run_id, {in_name}, "1",
                    retry_count=context.retry_number, max_user_code_retries={max_retries},
                    tags={tags}, extra_env={env_code})
                _add_step_metadata(context, task_path)
                _branch = _get_condition_branch(run_id, "{node.name}", "1")
                yield Output(task_path, output_name=_branch)
        """)

    # condition merge op ───────────────────────────────────────────────────────

    def _render_condition_merge_op(self, node) -> str:
        """Generate @op for a step that merges condition branches (follows split-switch)."""
        branches = node.in_funcs
        ins_parts = [f'"{p}": In(Optional[str], default_value=None)' for p in branches]
        ins_spec = "{" + ", ".join(ins_parts) + "}"
        args = ", ".join(branches)
        paths_list = "[" + ", ".join(branches) + "]"
        tags = repr(self.tags)
        env_code = self._extra_env_code(node)
        max_retries, _ = self._get_retry_info(node)
        deco = self._op_decorator_str(node, ins_spec=ins_spec, out_spec="Out(str)")
        return dedent(f"""\
            {deco}
            def {self._op_name(node.name)}(context: OpExecutionContext, {args}) -> str:
                input_path = next(p for p in {paths_list} if p is not None)
                run_id = input_path.split("/")[0]
                task_path = _run_step(context, "{node.name}", run_id, input_path, "1",
                    retry_count=context.retry_number, max_user_code_retries={max_retries},
                    tags={tags}, extra_env={env_code})
                _add_step_metadata(context, task_path)
                return task_path
        """)

    # ── Foreach chain analysis ─────────────────────────────────────────────────

    def _foreach_chains(self) -> dict[str, list]:
        if self._foreach_chains_cache is None:
            self._foreach_chains_cache = self._compute_foreach_chains()
        return self._foreach_chains_cache

    def _compute_foreach_chains(self) -> dict[str, list]:
        """Return {outermost_foreach: chain} for every outermost foreach in the flow.

        Each chain is a list of (foreach_name, body_name, join_name) tuples ordered
        outermost-first.  The chain ends when body_name is NOT itself a foreach step,
        so len(chain) == 1 for a simple (non-nested) foreach.
        """
        # foreach step name -> immediate body step name
        foreach_body: dict[str, str] = {}
        for node in self._topological_order():
            if node.type == "foreach" and node.out_funcs:
                foreach_body[node.name] = node.out_funcs[0]

        # foreach steps that are themselves the body of another foreach
        nested_foreach = {body for body in foreach_body.values() if body in foreach_body}
        # outermost = foreach steps not nested inside another foreach
        outermost = [name for name in foreach_body if name not in nested_foreach]

        # Pre-build lookup: split_step_name -> join_step_name (avoids O(n²) inner scan)
        split_to_join: dict[str, str] = {
            node.split_parents[-1]: node.name
            for node in self._topological_order()
            if node.type == "join" and node.split_parents
        }

        chains: dict[str, list] = {}
        for outer in outermost:
            chain: list = []
            current = outer
            while True:
                body = foreach_body[current]
                join = split_to_join.get(current)
                if join is None:
                    break
                chain.append((current, body, join))
                if body in foreach_body:
                    current = body
                else:
                    break
            if chain:
                chains[outer] = chain

        return chains

    # ── Compound op for nested foreach chains ─────────────────────────────────

    def _compound_op_name(self, outer_foreach_name: str) -> str:
        """Name for the compound op that handles the body of an outer foreach."""
        return f"op_{outer_foreach_name}__body"

    def _render_nested_foreach_compound_op(self, chain: list) -> str:
        """Generate a compound op for the body of an outer foreach in a nested chain.

        Dagster cannot have an op be downstream of more than one dynamic output
        (nested .map() is not supported).  For any foreach chain of depth > 1 we
        therefore generate a single @op that:

          1.  Receives the outer foreach's DynamicOutput value (encoded path + //_i=N).
          2.  Runs the outer body step (which is itself a foreach step).
          3.  Loops over inner foreach splits.
          4.  For each inner split runs the leaf body step(s).
          5.  Runs the inner join step to collect inner results.
          6.  Returns the inner join task path.

        This op is then used with .map() on the outer foreach's DynamicOutput so
        that the outer join can use .collect() on the results.
        """
        outer_foreach_name = chain[0][0]
        compound_name = self._compound_op_name(outer_foreach_name)
        in_name = outer_foreach_name
        ins_spec = self._ins_spec(in_name)

        body_lines = self._compound_op_body_lines(chain, param_name=in_name)
        body_text = "\n".join(f"    {line}" for line in body_lines)
        return (
            f"@op(ins={ins_spec}, out=Out(str))\n"
            f"def {compound_name}(context: OpExecutionContext, {in_name}: str) -> str:\n"
            f"{body_text}\n"
        )

    def _compound_op_body_lines(self, chain: list, param_name: str) -> list[str]:
        """Generate body lines for a compound op that handles nested foreach.

        The compound op is the BODY used with .map() on the outermost foreach's
        DynamicOutput.  chain[0] = (outer_foreach, outer_body=inner_foreach, outer_join).
        The compound op:
          - Receives the outer_foreach's DynamicOutput value ("run_id/step/tid//_i=N")
          - Does NOT re-run outer_foreach (already run by op_outer_foreach in the job)
          - Runs outer_body (chain[0][1]) which is itself a foreach step
          - Recursively handles deeper levels using chain[1:]
          - Runs the innermost join (chain[-1][2])
          - Returns the innermost join's task path
          - outer_join (chain[0][2]) is handled EXTERNALLY via .collect()

        For chain = [(start, outer_step, outer_join), (outer_step, inner_step, inner_join)]:
          1. Decode "run_id/start/1//_i=N" -> run_id, outer_foreach_task_id="1", outer_split=N
          2. Run outer_step at task_id "1-N" with input = "run_id/start/1"
          3. Read outer_step's num_splits
          4. For each _i in range(num_splits):
               Run inner_step at task_id "1-N-{_i}"
               Append inner_step path to results
          5. Run inner_join at task_id "1-N-join"
          6. return inner_join path
        """
        tags_code = repr(self.tags)


        result_lines: list[str] = []

        # Decode outer DynamicOutput value
        result_lines.append(f"_parts = {param_name}.split('//_i=')")
        result_lines.append("_base_path = _parts[0]")
        result_lines.append("_outer_split = int(_parts[1]) if len(_parts) > 1 else 0")
        result_lines.append("run_id = _base_path.split('/')[0]")
        result_lines.append("_outer_fe_tid = _base_path.rsplit('/', 1)[-1]")

        inner_chain = chain[1:]  # chain starting from the inner_foreach level

        def _emit(depth: int, pfx: str, parent_path_expr: str, parent_task_id_var: str, split_var: str) -> str:
            """Emit code for inner_chain[depth].  Returns the join_path variable name."""
            foreach_name, body_name, join_name = inner_chain[depth]
            idx = self._LOOP_IDX[depth] if depth < len(self._LOOP_IDX) else f"_idx_{depth}"

            foreach_node = self.graph[foreach_name]
            foreach_env = self._extra_env_code(foreach_node)
            foreach_max_retries, _ = self._get_retry_info(foreach_node)
            join_node = self.graph[join_name]
            join_env = self._extra_env_code(join_node)
            join_max_retries, _ = self._get_retry_info(join_node)

            # Task IDs and variable names unique per depth
            fe_tid_var = f"_fe_tid_{depth}"
            fe_path_var = f"_fe_path_{depth}"
            results_var = f"_res_{depth}"
            join_tid_var = f"_join_tid_{depth}"
            join_path_var = f"_join_path_{depth}"

            # Compute foreach step's task_id from parent
            result_lines.append(f'{pfx}{fe_tid_var} = {parent_task_id_var} + "-" + str({split_var})')

            # Run the foreach step
            result_lines.append(f"{pfx}{fe_path_var} = _run_step(")
            result_lines.append(f"{pfx}    context, {foreach_name!r}, run_id, {parent_path_expr},")
            result_lines.append(f"{pfx}    {fe_tid_var},")
            result_lines.append(f"{pfx}    retry_count=context.retry_number,")
            result_lines.append(f"{pfx}    max_user_code_retries={foreach_max_retries},")
            result_lines.append(f"{pfx}    tags={tags_code},")
            result_lines.append(f"{pfx}    split_index={split_var},")
            result_lines.append(f"{pfx}    extra_env={foreach_env},")
            result_lines.append(f"{pfx})")
            result_lines.append(f"{pfx}_add_step_metadata(context, {fe_path_var})")

            # Read num_splits
            result_lines.append(f"{pfx}_ns_{depth} = _get_foreach_splits(run_id, {foreach_name!r}, {fe_tid_var})")

            # Loop over splits
            result_lines.append(f"{pfx}{results_var} = []")
            result_lines.append(f"{pfx}for {idx} in range(_ns_{depth}):")

            if depth == len(inner_chain) - 1:
                # Innermost: body_name is a regular (non-foreach) step
                body_node = self.graph[body_name]
                body_env = self._extra_env_code(body_node)
                body_max_retries, _ = self._get_retry_info(body_node)
                body_tid_var = f"_body_tid_{depth}"
                body_path_var = f"_body_path_{depth}"
                result_lines.append(f'{pfx}    {body_tid_var} = {fe_tid_var} + "-" + str({idx})')
                result_lines.append(f"{pfx}    {body_path_var} = _run_step(")
                result_lines.append(f"{pfx}        context, {body_name!r}, run_id, {fe_path_var},")
                result_lines.append(f"{pfx}        {body_tid_var},")
                result_lines.append(f"{pfx}        retry_count=context.retry_number,")
                result_lines.append(f"{pfx}        max_user_code_retries={body_max_retries},")
                result_lines.append(f"{pfx}        tags={tags_code},")
                result_lines.append(f"{pfx}        split_index={idx},")
                result_lines.append(f"{pfx}        extra_env={body_env},")
                result_lines.append(f"{pfx}    )")
                result_lines.append(f"{pfx}    _add_step_metadata(context, {body_path_var})")
                result_lines.append(f"{pfx}    {results_var}.append({body_path_var})")
            else:
                # body is itself a foreach step: recurse (body_name == inner_chain[depth+1][0])
                inner_join_var = _emit(depth + 1, pfx + "    ", fe_path_var, fe_tid_var, idx)
                result_lines.append(f"{pfx}    {results_var}.append({inner_join_var})")

            # After loop: run join
            result_lines.append(f"{pfx}_ji_{depth} = compress_list({results_var})")
            result_lines.append(f'{pfx}{join_tid_var} = {fe_tid_var} + "-join"')
            result_lines.append(f"{pfx}{join_path_var} = _run_step(")
            result_lines.append(f"{pfx}    context, {join_name!r}, run_id, _ji_{depth},")
            result_lines.append(f"{pfx}    {join_tid_var},")
            result_lines.append(f"{pfx}    retry_count=context.retry_number,")
            result_lines.append(f"{pfx}    max_user_code_retries={join_max_retries},")
            result_lines.append(f"{pfx}    tags={tags_code},")
            result_lines.append(f"{pfx}    extra_env={join_env},")
            result_lines.append(f"{pfx})")
            result_lines.append(f"{pfx}_add_step_metadata(context, {join_path_var})")
            return join_path_var

        # Emit depth 0: foreach step is inner_chain[0][0], input is _base_path,
        # task_id prefix is _outer_fe_tid with split index _outer_split.
        final_var = _emit(0, "", "_base_path", "_outer_fe_tid", "_outer_split")
        result_lines.append(f"return {final_var}")
        return result_lines

    # ── Job body ───────────────────────────────────────────────────────────────

    def _render_job(self) -> str:
        body = self._generate_job_body()
        # Build manually — dedent(f"""...""") mishandles multi-line substitutions
        body_indented = "\n".join("    " + line for line in body.splitlines())
        job_args = f'(tags={{"dagster/max_runtime": "{self.workflow_timeout}"}})' if self.workflow_timeout else ""
        return f"@job{job_args}\ndef {self.job_name}():\n{body_indented}\n"

    def _generate_job_body(self) -> str:
        """
        Walk topologically ordered nodes and emit assignment statements.
        var_map: step_name -> Python expression for its output.

        For nested foreach chains (depth > 1), steps inside the chain are handled
        by the compound op and are therefore skipped in the top-level job body.
        The compound op is wired via .map() on the outer foreach's DynamicOutput
        and its result (the inner join's task path) is used by .collect() for the
        outer join.
        """
        lines: list[str] = []
        var_map: dict[str, str] = {}

        chains = self._foreach_chains()
        steps_in_compound = self._steps_in_compound()

        def _emit(node) -> None:
            # Skip steps handled inside compound ops
            if node.name in steps_in_compound:
                return

            op_call = self._op_name(node.name)
            ntype = node.type

            # ── start step ────────────────────────────────────────────────────
            if node.name == "start":
                var = "r_start"
                lines.append(f"{var} = {op_call}()")
                var_map["start"] = var
                if ntype in ("split", "split-switch"):
                    for branch in node.out_funcs:
                        var_map[f"_branch_{branch}"] = f"{var}.{branch}"
                elif ntype == "foreach" and "start" in chains and len(chains["start"]) > 1:
                    compound_name = self._compound_op_name("start")
                    compound_var = "r_start__body"
                    lines.append(f"{compound_var} = {var}.map({compound_name})")
                    outer_body_name = chains["start"][0][1]
                    var_map[outer_body_name] = compound_var

            # ── end step ──────────────────────────────────────────────────────
            elif ntype == "end":
                pvar = self._resolve_input(node, var_map)
                lines.append(f"{op_call}({pvar})")
                var_map[node.name] = "_end"

            # ── linear step ───────────────────────────────────────────────────
            elif ntype == "linear":
                foreach_parent = next(
                    (p for p in node.in_funcs if self.graph[p].type == "foreach"),
                    None,
                )
                var = f"r_{node.name}"
                if foreach_parent is not None:
                    dyn_var = var_map[foreach_parent]
                    lines.append(f"{var} = {dyn_var}.map({op_call})")
                elif self._is_condition_merge(node):
                    kwargs = ", ".join(f"{p}={var_map.get(p, p)}" for p in node.in_funcs)
                    lines.append(f"{var} = {op_call}({kwargs})")
                else:
                    pvar = self._resolve_input(node, var_map)
                    lines.append(f"{var} = {op_call}({pvar})")
                var_map[node.name] = var

            # ── split step ────────────────────────────────────────────────────
            elif ntype == "split":
                pvar = self._resolve_input(node, var_map)
                var = f"r_{node.name}"
                lines.append(f"{var} = {op_call}({pvar})")
                var_map[node.name] = var
                for branch in node.out_funcs:
                    var_map[f"_branch_{branch}"] = f"{var}.{branch}"

            # ── split-switch (condition) step ─────────────────────────────────
            elif ntype == "split-switch":
                pvar = self._resolve_input(node, var_map)
                var = f"r_{node.name}"
                lines.append(f"{var} = {op_call}({pvar})")
                var_map[node.name] = var
                for branch in node.out_funcs:
                    var_map[f"_branch_{branch}"] = f"{var}.{branch}"

            # ── foreach step ──────────────────────────────────────────────────
            elif ntype == "foreach":
                pvar = self._resolve_input(node, var_map)
                var = f"r_{node.name}"
                lines.append(f"{var} = {op_call}({pvar})")
                var_map[node.name] = var
                if node.name in chains and len(chains[node.name]) > 1:
                    compound_name = self._compound_op_name(node.name)
                    compound_var = f"r_{node.name}__body"
                    lines.append(f"{compound_var} = {var}.map({compound_name})")
                    outer_body_name = chains[node.name][0][1]
                    var_map[outer_body_name] = compound_var

            # ── join step ─────────────────────────────────────────────────────
            elif ntype == "join":
                var = f"r_{node.name}"
                if self._is_foreach_join(node):
                    body_step = node.in_funcs[0]
                    if body_step in steps_in_compound:
                        outer_foreach_name = node.split_parents[-1]
                        outer_body_name = chains[outer_foreach_name][0][1]
                        dyn_var = var_map[outer_body_name]
                    else:
                        dyn_var = var_map[body_step]
                    lines.append(f"{var} = {op_call}({dyn_var}.collect())")
                else:
                    in_vars = [var_map.get(p, p) for p in node.in_funcs]
                    lines.append(f"{var} = {op_call}({', '.join(in_vars)})")
                var_map[node.name] = var

        for node in self._topological_order():
            _emit(node)

        return "\n".join(lines) if lines else "pass"

    def _resolve_input(self, node, var_map: dict[str, str]) -> str:
        """Get the Python expression for the first upstream input to this node."""
        parent = node.in_funcs[0] if node.in_funcs else None
        if parent is None:
            return "None"
        # Check if there's a named branch output for this step
        branch_key = f"_branch_{node.name}"
        if branch_key in var_map:
            return var_map[branch_key]
        return var_map.get(parent, parent)

    # ── Schedule ───────────────────────────────────────────────────────────────

    _SCHEDULE_CRON = {"daily": "0 0 * * *", "hourly": "0 * * * *", "weekly": "0 0 * * 0"}

    def _extract_schedule(self) -> str | None:
        sched = self.flow._flow_decorators.get("schedule")
        if not sched:
            return None
        sched = sched[0]
        if sched.attributes.get("cron"):
            return sched.attributes["cron"]
        for key, cron in self._SCHEDULE_CRON.items():
            if sched.attributes.get(key):
                return cron
        return None

    def _render_schedule(self) -> str:
        return dedent(f"""\
            {self.job_name}_schedule = ScheduleDefinition(
                job={self.job_name},
                cron_schedule={self.schedule!r},
            )
        """)

    # ── Trigger / trigger_on_finish extraction ─────────────────────────────────

    def _extract_triggers(self) -> list[dict]:
        """Return a list of {event_name, parameter_map} dicts from @trigger."""
        import warnings
        decos = self.flow._flow_decorators.get("trigger")
        if not decos:
            return []
        raw_triggers = getattr(decos[0], "triggers", None) or []
        result = []
        for t in raw_triggers:
            if not isinstance(t, dict):
                continue
            name = t.get("name")
            if not name or not isinstance(name, str):
                warnings.warn(
                    f"@trigger entry has a non-string or deploy-time event name {name!r} — "
                    "skipping this trigger. Evaluate the event name before deploying.",
                    UserWarning,
                    stacklevel=2,
                )
                continue
            raw_params = t.get("parameters") or {}
            param_map = dict(raw_params) if isinstance(raw_params, dict) else {}
            result.append({"event_name": name, "parameter_map": param_map})
        return result

    def _extract_trigger_on_finishes(self) -> list[dict]:
        """Return a list of {flow_name} dicts from @trigger_on_finish."""
        import warnings
        decos = self.flow._flow_decorators.get("trigger_on_finish")
        if not decos:
            return []
        raw_triggers = getattr(decos[0], "triggers", None) or []
        result = []
        for t in raw_triggers:
            if not isinstance(t, dict):
                continue
            flow_name = t.get("flow") or t.get("fq_name")
            if not flow_name or not isinstance(flow_name, str):
                warnings.warn(
                    f"@trigger_on_finish entry has a non-string or missing flow name {flow_name!r} — "
                    "skipping this trigger.",
                    UserWarning,
                    stacklevel=2,
                )
                continue
            result.append({"flow_name": flow_name})
        return result

    # ── Sensor rendering ───────────────────────────────────────────────────────

    def _render_sensors(self) -> list[str]:
        """Emit sensor definitions for @trigger and @trigger_on_finish decorators."""
        sensors = []
        for i, t in enumerate(self.triggers):
            sensors.append(self._render_event_sensor(t, i))
        for i, t in enumerate(self.trigger_on_finishes):
            sensors.append(self._render_finish_sensor(t, i))
        return sensors

    def _render_event_sensor(self, trigger: dict, idx: int) -> str:
        event_name = trigger["event_name"]
        param_map = trigger["parameter_map"]
        sensor_name = f"{self.job_name}_on_event_{idx}"
        # Build run_config snippet when there are parameter mappings
        if param_map:
            run_config_lines = (
                "        run_config = {\n"
                '            "ops": {"start": {"config": {\n'
            )
            for flow_param, event_field in param_map.items():
                run_config_lines += (
                    f'                {flow_param!r}: context.cursor or "",  '
                    f"# mapped from event field {event_field!r}\n"
                )
            run_config_lines += "            }}}\n        }\n"
        else:
            run_config_lines = "        run_config = {}\n"

        return dedent(f"""\
            @sensor(job={self.job_name}, name={sensor_name!r}, default_status=DefaultSensorStatus.RUNNING)
            def {sensor_name}(context: SensorEvaluationContext):
                \"\"\"Fire {self.job_name} when the '{event_name}' event is detected.

                Dagster does not have a native event-bus — this sensor polls for the event
                by checking a cursor value.  Emit a RunRequest whenever you detect the event
                (e.g., by reading a queue, a file marker, or an external API).
                \"\"\"
                # TODO: replace this stub with real event-detection logic.
                # Example: read from a queue, a DB table, or an HTTP endpoint.
                event_detected = False  # set to True when the event arrives
                if event_detected:
            {run_config_lines}        yield RunRequest(run_key=context.cursor, run_config=run_config)
        """)

    def _render_finish_sensor(self, trigger: dict, idx: int) -> str:
        upstream_flow = trigger["flow_name"]
        upstream_job = upstream_flow  # Dagster job name defaults to the flow name
        sensor_name = f"{self.job_name}_on_finish_{idx}"
        return dedent(f"""\
            @sensor(job={self.job_name}, name={sensor_name!r}, default_status=DefaultSensorStatus.RUNNING)
            def {sensor_name}(context: SensorEvaluationContext):
                \"\"\"Fire {self.job_name} when Dagster job '{upstream_job}' completes successfully.

                This sensor watches the Dagster run history for successful runs of the
                upstream job (compiled from the '{upstream_flow}' Metaflow flow) and
                triggers a new run of {self.job_name} for each new completion.
                \"\"\"
                from dagster import DagsterInstance, RunsFilter, DagsterRunStatus
                instance = context.instance
                last_cursor = context.cursor or "0"
                runs = instance.get_runs(
                    filters=RunsFilter(
                        job_name={upstream_job!r},
                        statuses=[DagsterRunStatus.SUCCESS],
                    ),
                    limit=50,
                )
                new_cursor = last_cursor
                for run in runs:
                    run_key = run.run_id
                    if run_key > last_cursor:
                        yield RunRequest(run_key=run_key)
                        if run_key > new_cursor:
                            new_cursor = run_key
                context.update_cursor(new_cursor)
        """)

    # ── Definitions ────────────────────────────────────────────────────────────

    def _render_definitions(self) -> str:
        sched_list = f"[{self.job_name}_schedule]" if self.schedule else "[]"
        sensor_names = []
        for i in range(len(self.triggers)):
            sensor_names.append(f"{self.job_name}_on_event_{i}")
        for i in range(len(self.trigger_on_finishes)):
            sensor_names.append(f"{self.job_name}_on_finish_{i}")
        if sensor_names:
            sensors_list = "[" + ", ".join(sensor_names) + "]"
        else:
            sensors_list = "[]"
        return dedent(f"""\
            defs = Definitions(
                jobs=[{self.job_name}],
                schedules={sched_list},
                sensors={sensors_list},
            )
        """)

